### ISSUE TITLE
Import images from remote

### ISSUE THREAD

**Issue by He110te4m** [module-federation/vite#10]
I tried importing images in a remote project with an import statement.

The final parsed image request is not taken over by es-module-polyfill, but by the browser.

Causes remote image resources to not be used properly.

So I need config remote base and host proxy to forward the request.

However, when I added the base configuration to remote, nothing worked.

e.g. `remoteEntry.json` can not be found and the shared deps import name has been changed.

Does this plugin support configuring `base`?

Or do I need to do something extra?

It should be noted that this functionality is normal for builds, and esbuild-plugin-inline-image is able to build images into base64, but does not take effect in Dev.

**Comment by gioboa** [comment]
🤔 Have you got a basic reproduction repo?

**Comment by He110te4m** [comment]
Yes, I just made one.

https://github.com/He110te4m/module-federation-issue-10-reproduction-repo

**Comment by He110te4m** [comment]
Thanks.
Looking forward to your good news.

**Comment by He110te4m** [comment]
I found a way to use `import.meta.url` modifies the image address of import in the TS file.

Imports in CSS need to be replaced manually with the `postcss-url` plugin.

It was a temporary solution, but it was strange.

From a maintainable point of view, proxy is more appropriate.

**Comment by gioboa** [comment]
Can you share me the code pls?

**Comment by He110te4m** [comment]
I needed a little more time, and found that the images used in CSS needed to be processed separately in esbuild.

You can use this plugin if you are importing images directly from a file such as TS or Vue:

```
import { type Plugin } from 'vite'

const defaultSuffixes: string[] = [
  'png', 'webp', 'jpg', 'gif',
  'jpeg', 'tiff', 'svg', 'bmp',
]

export interface PluginOptions {
  suffixes?: string[]
}

export default function transformImageUrlPlugin({ suffixes = defaultSuffixes }: PluginOptions = {}): Plugin {
  const staticResourceReg = new RegExp(`\\.(${suffixes.join('|')})($|\\?)`)

  return {
    name: '@dsp-plugins/vite-static-url',
    transform(code, id) {
      if (staticResourceReg.test(id)) {
        return {
          code: code.replace(
            /(export\s+default)\s+(".+")/,
            '$1 new URL($2, import.meta[\'url\']).href',
          ),
          map: null,
        }
      }
      return undefined
    },
  }
}
```

**Comment by He110te4m** [comment]
Although this solves my problem, I think it would be more convenient to use proxy.

This solution must be built with the server address in mind, and can not be adapted to various environments.

Although this solves my problem, I think it would be more convenient to use proxy.

This solution must be built with the server address in mind, and can not be adapted to various environments.

Unless the Nginx forwarding address is used.

But the nginx configuration also needs to be build-time generated, which involves too many steps.

**Comment by gioboa** [comment]
Nice 🙂 will you use this solution or something base on proxy? Can we close the issue?

**Comment by He110te4m** [comment]
If this problem is just dealing with image loading, I think it can be turned off.

However, as mentioned earlier, there is still a problem with vite configuring base to not open the page properly.

Maybe we can open a new issue to track this?

**Comment by gioboa** [comment]
yep, let's close this one and we can create a specific one for the `base` issue
