### ISSUE TITLE
Dynamic runtime remotes

### ISSUE THREAD

**Issue by 0x0dr1y** [module-federation/vite#102]
Hey, 

i'm currently using originjs/vite-plugin-federation and am considering to switch to this plugin. In the other plugin I'm able to load remotes at runtime like this: 

```import { __federation_method_setRemote, __federation_method_getRemote } from '__federation__'

const RemoteApp = lazy(() => {
	__federation_method_setRemote('remote-app', {
		url: () => Promise.resolve('http://localhost:8080/assets/remote-entry.js'),
		format: 'esm',
		from: 'vite'
	})

	return __federation_method_getRemote('remote-app', './App')
})

const App = () => {
      return <RemoteApp />
}
````

Is something like this also possible within this plugin? I saw the answer in https://github.com/module-federation/vite/issues/12 but it seems like two different concepts.

Thanks!

**Comment by zhangHongEn** [comment]
https://module-federation.io/guide/basic/runtime.html

**Comment by gioboa** [comment]
@0x0dr1y yes, you can.
Check [this React example](https://github.com/gioboa/react-microfrontend-demo/blob/main/host%2Fsrc%2FApp.tsx#L7) 😉

**Comment by 0x0dr1y** [comment]
Thanks @zhangHongEn. I will have a look
