### ISSUE TITLE
 On-Demand Loading of remoteEntry.js Files

### ISSUE THREAD

**Issue by judithhartmann** [module-federation/vite#103]
I am currently evaluating a migration from the @originjs plugin. One of the things I liked about their approach was, that they only try to load the remoteEntry.js once a module is required in the code.

Our use case involves many modules behind feature flags. As a result, not all modules are active in a given environment, and pre-loading all remoteEntry.js files can lead to 404 errors or application crashes if a particular remoteEntry.js file is not available when the site initially loads.

Question: Is there a way to configure this plugin to load the remoteEntry.js of a module only when that module is accessed for the first time at runtime? This would significantly improve resilience and performance in environments with varying feature flags.

I have seen https://module-federation.io/guide/basic/runtime.html but since our config does not really change, i would like to keep the config within our vite config

**Comment by zhangHongEn** [comment]
Modules that have never been used will not be requested

**Comment by zhangHongEn** [comment]
If you only configure remotes in vite.config.js and don't import it, remoteEntry.js will not be requested.

**Comment by judithhartmann** [comment]
We have code like this:
`() => import('moduleShop/ShopApp')`that is called asynchronously when the user enters the shop page (useEffect hook on mount). We never have moduleShop as an import on top of a file.

With origin js, i can see the network request to the moduleShop remoteEntry.js file being dispatched once the user enters the page that embeds the shop module. With this plugin, the remoteEntry.js file is loaded on the very first page.

**Comment by zhangHongEn** [comment]
During the normal initialization phase, all shared modules need to be registered. The lazy loading you mentioned is another mode.

**Comment by zhangHongEn** [comment]
Lazy loading mode needs to be implemented through runtime plugins

**Comment by judithhartmann** [comment]
Using runtime plugins has some disadvantages though (sharing dependencies seems to be much more complicated).

Can't we introduce a mode to this plugin, that initializes a remote only on first use, instead of during the normal initialization phase?

**Comment by zhangHongEn** [comment]
https://github.com/module-federation/core/pull/2984

**Comment by judithhartmann** [comment]
I could not find a documentation of this parameter, what it is doing and possible options. 

Do you have information on that? (Or is it introduced in this PR, but no documentation is added yet?)

**Comment by zhangHongEn** [comment]
I haven't seen this PR yet, it should be supported soon

---- Replied Message ----
| From | Judith ***@***.***> |
| Date | 09/25/2024 18:33 |
| To | module-federation/vite ***@***.***> |
| Cc | zhn ***@***.***>,
Comment ***@***.***> |
| Subject | Re: [module-federation/vite] On-Demand Loading of remoteEntry.js Files (Issue #103) |

I could not find a documentation of this parameter, what it is doing and possible options.

Do you have information on that? (Or is it introduced in this PR, but no documentation is added yet?)

**Comment by zhangHongEn** [comment]
Wait for me to find time tonight to take a look

---- Replied Message ----
| From | Judith ***@***.***> |
| Date | 09/25/2024 18:33 |
| To | module-federation/vite ***@***.***> |
| Cc | zhn ***@***.***>,
Comment ***@***.***> |
| Subject | Re: [module-federation/vite] On-Demand Loading of remoteEntry.js Files (Issue #103) |

I could not find a documentation of this parameter, what it is doing and possible options.

Do you have information on that? (Or is it introduced in this PR, but no documentation is added yet?)

**Comment by artuska** [comment]
I try to move from the @originjs to the @module-federation.

When i try to lazy import the remote, eg:

```
import { lazy } from "react";
const Settings = lazy(() => import("iplatform_client_settings/App"));
```

i get an error:

```
Uncaught SyntaxError: Cannot use import statement outside a module (at remoteEntry.js:1:1)
```

When i try to simple import the remote, eg:

```
import Header from "iplatform_client_header/App";
```

i get an error:

```
Uncaught Error: [ Federation Runtime ]: remoteEntryExports is undefined 
 {
  "entryGlobalName": "iplatform_client_header",
  "name": "iplatform_client_header",
  "type": "var",
  "entry": "http://localhost:4001/apps/iplatform-client-header/remoteEntry.js",
  "shareScope": "default"
}
    at error2 (index.cjs.js:21:11)
    at assert2 (index.cjs.js:13:9)
    at Module.getEntry (index.cjs.js:1217:9)
    at async Module.get (index.cjs.js:1227:36)
    at async RemoteHandler.loadRemote (index.cjs.js:2558:37)
    at async iplatform_client_header_App.js:24:1
```

I'm just trying to implement the simpliest code copy-paste from the @module-federation/vite readme page and from examples... and it just does not work at all.

**Comment by gioboa** [comment]
Hi @artuska I'm sorry about that, did you try the react example?

**Comment by artuska** [comment]
I have the same problem — @module-federation/vite downloads absolutely all `remoteEntry.js` files from the Host app, then it downloads all `remoteEntry.js` files from the Remote apps which consumes other remotes (i have ~60 microfrontends in my NX application).

After it has downloaded all `remoteEntry.js` files it starts to download absolutely all other files which are imported in `remoteEntry.js`.

Why is this?

**Comment by gioboa** [comment]
@artuska Hi, can you create a reproduction repository please?
