### ISSUE TITLE
Empty react in production build

### ISSUE THREAD

**Issue by romanopassalacqua** [module-federation/vite#11]
I'm trying to create a simple react remote app that exposes 1 component. When I run Vite in `dev` mode it works, but when I run it in `prod` I get a blank page with the following error on the console:

```
Uncaught (in promise) SyntaxError: The requested module 'blob:http://127.0.0.1:3000/e5043e10-c7d6-4c8f-82a0-302742fc648d' does not provide an export named 'useState' (at bootstrap-b136d97a.js:1:144)
await (async)
(anonymous) @ index-dd854aaa.js:14
```

Checking the dist folder, some files from react are empty and reference development files instead of production.

I looked at #3 (specifically https://github.com/module-federation/vite/issues/3#issuecomment-1445047531) but downgrading doesn't solve the issue, downgrading breaks `dev` mode. 

Also, [the react example referenced on README.md](https://github.com/module-federation/module-federation-examples/tree/master/vite-react-microfrontends) doesn't work. It uses the `1.1.0` from `@softarc/native-federation` which doesn't work in `dev` or `prod` mode.

[Reproduction repo](https://github.com/romanopassalacqua/vite-react-remote)

**Comment by gioboa** [comment]
Hi, did you see this example?
https://github.com/gioboa/react-microfrontend-demo
You should import
`import React from 'react';`
and then use `React.useState`

**Comment by romanopassalacqua** [comment]
Hi, I didn't know about your example.

I tried your suggestion and the useState error disappeared, but now I get:

```
Uncaught (in promise) TypeError: a.createRoot is not a function
    at bootstrap-7a01b129.js:1:1027
```

This error also occurs in your example when in `prod` mode.

**Comment by gioboa** [comment]
Same trick for that 
https://github.com/gioboa/react-microfrontend-demo/blob/ba902526d108b22e00a98d1a4a6fc1ee24d8bf44/remote/src/bootstrap.tsx#L5

**Comment by romanopassalacqua** [comment]
I'm sorry, but what do you mean by "same trick"? I already have [that](https://github.com/romanopassalacqua/vite-react-remote/blob/056c31947a6ed5ff5a0423496b2355f96d3404bc/src/bootstrap.tsx#L6). 

As I said in https://github.com/module-federation/vite/issues/11#issuecomment-1633712382 your example also gives the error in `prod` mode.

I think the main problem is that in the generated bundle react is empty
``` 
var e={exports:{}};var t=e.exports;export{t as default};
/**
 * @license React
 * react.development.js
 *
 * Copyright (c) Facebook, Inc. and its affiliates.
 *
 * This source code is licensed under the MIT license found in the
 * LICENSE file in the root directory of this source tree.
 */
/*Try to compensate missing exports*/
```

**Comment by gioboa** [comment]
I see, I will look at it in these days.
Thanks for the feedback, appreciate

**Comment by gioboa** [comment]
Are you using npm or yarn/pnpm?

**Comment by He110te4m** [comment]
Maybe you can check to see if react is shared.

You can look at the number of react files in the network. It should only be one.

Because part of  `useEffect` is determined when the module is initialized, if react doesn't share it, it will cause useEffect to fail.

**Comment by romanopassalacqua** [comment]
> Are you using npm or yarn/pnpm?

I'm using npm

**Comment by romanopassalacqua** [comment]
> Maybe you can check to see if react is shared.
> 
> You can look at the number of react files in the network. It should only be one.
> 
> Because part of `useEffect` is determined when the module is initialized, if react doesn't share it, it will cause useEffect to fail.

Yes, I do have [react shared](https://github.com/romanopassalacqua/vite-react-remote/blob/056c31947a6ed5ff5a0423496b2355f96d3404bc/module-federation/federation.config.cjs#L8) and this is quite important to know because the error only occurs when I share my dependencies. If I leave an empty object in `shared` everything works, but this is a remote which will be used in a host so react needs to be shared.

**Comment by He110te4m** [comment]
No, I think there may be some misunderstanding.

After configuring shared here, there is not necessarily only one request.

For example, an alias exists in tsconfig or is configured in Vite.

These will cause react to get content from two different urls.

So the way to see if the same react or other library is actually shared is to look at the request in the network.

**Comment by christophediprima** [comment]
Hi there! I am having the same issue, but it comes from an external package that is importing react hooks.

```
_apollo_client-3_7_9-prod.js:1 Uncaught (in promise) SyntaxError: The requested module 'blob:http://localhost:1337/249c35f7-403e-41e5-9066-d6d4d3041e21' does not provide an export named 'useState' (at _apollo_client-3_7_9-prod.js:1:136)
await (async)
(anonymous) @ index-3faf5f55.js:1
(anonymous) @ index-3faf5f55.js:1
```

**Comment by gioboa** [comment]
@christophediprima did you solve the problem?

**Comment by seravifer** [comment]
I have the same problem, @gioboa have you been able to find out what's happening?

**Comment by gioboa** [comment]
I didn't investigate into it yet 👀

**Comment by jucian0** [comment]
Same problem here 
Uncaught (in promise) TypeError: s.createRoot is not a function

**Comment by ptz000** [comment]
the same here, 
createRoot is correctly exported from 'react-dom/client',
react-dom/client is correctly shared between the remotes/host
but it seems when importing createRoot in the application is undefined
I tried also to skip react-dom/client but createRoot is still undefined

**Comment by rhaddad94** [comment]
I found a workaround, setting `dev` to `true` into federation `options`:
```js
		await federation({
			options: {
				...
				dev: true,
			},
			...
		})
```

With this option react generated file is not empty anymore. But it's definitely hacky.

**Comment by gioboa** [comment]
The new version of `native-federation` seems brakes the process 😢

**Comment by IkhyeonKim** [comment]
Still, I got the same error here, any updates?

**Comment by gioboa** [comment]
Can you try with these deps pls?
```
"@module-federation/vite": "0.2.6",
"@softarc/native-federation": "1.1.2",
"@softarc/native-federation-esbuild": "1.1.1",
```
Pls let me know if it works for you

**Comment by jpikl** [comment]
I went through the [Git history](https://github.com/module-federation/module-federation-examples/commits/master/vite-react-microfrontends) and the last working commit is `d081c9dad5c379d9df8c57a95c1f1c2a07041809` with the following deps:

```
 "@module-federation/vite": "^0.2.6",
"@softarc/native-federation": "^1.1.0",
"@softarc/native-federation-esbuild": "^1.1.0",
```

what broke the example was the update of `@softarc/native-federation-esbuild` from `1.1.0` to `1.1.1` [here](https://github.com/module-federation/module-federation-examples/commit/8137f8df3823ff438201da2ebd31ac6065c7fafb#diff-9ebcfb493cdd241f286caf5a75b36f5e8f878537df40c911cdc8c3df0b941cb1)

**Comment by IkhyeonKim** [comment]
> I went through the [Git history](https://github.com/module-federation/module-federation-examples/commits/master/vite-react-microfrontends) and the last working commit is `d081c9dad5c379d9df8c57a95c1f1c2a07041809` with the following deps:
> 
> 
> 
> ```
> 
>  "@module-federation/vite": "^0.2.6",
> 
> "@softarc/native-federation": "^1.1.0",
> 
> "@softarc/native-federation-esbuild": "^1.1.0",
> 
> ```
> 
> 
> 
> what broke the example was the update of `@softarc/native-federation-esbuild` from `1.1.0` to `1.1.1` [here](https://github.com/module-federation/module-federation-examples/commit/8137f8df3823ff438201da2ebd31ac6065c7fafb#diff-9ebcfb493cdd241f286caf5a75b36f5e8f878537df40c911cdc8c3df0b941cb1)

Sorry for the late response. I downgraded the versions and it works! Thanks!!

**Comment by cristiano-belloni** [comment]
@gioboa this is not "completed" though. Why do we need to downgrade `@softarc/native-federation-esbuild` to make it work?

**Comment by cristiano-belloni** [comment]
Understood. Since this repo is the "official" module-federation support for
Vite, does the team plan to align it with the latest native-federation
version? I struggle finding changelogs and pinpoint what has changed and
what is supported in 0.2.x.

**Comment by cristiano-belloni** [comment]
See also this comment: https://github.com/module-federation/vite/issues/16#issuecomment-1913558770

Downgrading causes problems with peer dependencies, and the demo [here](https://github.com/module-federation/module-federation-examples/tree/master/vite-react-microfrontends) is broken.

**Comment by gioboa** [comment]
With Vite 5 in the future we will have a native mfes support. This packages would like to support all the frameworks, not only React, so we can cut a new release with the correct version of @softarc/native-federation, but this is not the optimal solution.

**Comment by cristiano-belloni** [comment]
Hey @gioboa, thanks for your answer.

> With Vite 5 in the future we will have a native mfes support. 

I'm not sure I understand. Vite 5 is currently out, I don't see native microfrontends in its current milestones: https://github.com/vitejs/vite/milestones?direction=asc&sort=title&state=open. What do you mean with "With Vite 5 in the future we will have a native mfes support"?

> This packages would like to support all the frameworks, not only React

Yes, but at the moment, as it is, it **does not** support React. I literally tried the [React](https://github.com/module-federation/module-federation-examples/tree/master/vite-react-microfrontends) link in the "Working implementations" section in your README without modification and I have exactly this issue.

> we can cut a new release with the correct version of @softarc/native-federation, but this is not the optimal solution.

I agree that the optimal solution would be keeping this bug open until someone fixes this plugin to support the latest version of @softarc/native-federation, but it looks like this issue has been closed and there's no plan to update the plugin, so I'm a bit lost.

**Comment by gioboa** [comment]
[Here](https://youtu.be/hrdwQHoAp0M?t=839) you can find the public announcement.
I'll fix the React example, thanks.

**Comment by seravifer** [comment]
I have managed to get the example working.
The problem comes because by default it is set to take the React dependencies in development. So it causes the build to remain empty. If you change it again later, it will use the version cached in the "node_modules/.temp" folder so React will still be empty.

It's a bit strange behavior to be honest, but it has caused all these problems. If you delete the caches and loop again the build works.
```js
			await federation({
				options: {
					workspaceRoot: __dirname,
					outputPath: 'dist',
					tsConfig: 'tsconfig.json',
					federationConfig: `module-federation/federation.config.cjs`,
					verbose: false,
					dev: command === 'serve',
				},
				adapter: createEsBuildAdapter({ plugins: [], fileReplacements: command === 'serve' ?  reactReplacements.dev : reactReplacements.prod }),
			}),
```

**Comment by gioboa** [comment]
Thanks @seravifer 
May I ask you to drop a PR to fix the official example?
