### ISSUE TITLE
feat: add e2e tests based on the examples

### ISSUE THREAD

**Issue by gioboa** [module-federation/vite#111]
The idea is to have e2e tests to verify that the package is working as expected.
We can use the examples for that.

**Comment by bidodev** [comment]
Hey  @gioboa, first of all, thanks for this plugin and all the hard work! Currently, we're using another one, but we are already testing this one for production.

I saw your request and would like to contribute. I plan to test it using Playwright, but I have a few questions before proceeding.

Do you have the examples deployed somewhere? If so, I can set up Playwright in the repository and create some e2e tests for each example.

If they're not deployed, could we maybe use GitHub Pages for that? Or do you have something else in mind?

Once I get clearance, I'll be ready to start working on it.

**Comment by gioboa** [comment]
Hi @bidodev thanks for your help.
We don't have any deployment yet, in this PR #57 we suggested GH pages. 
I think we can run the e2e with a GH action so there is no need of deployment.
I'm looking forward to hearing your thoughts.

**Comment by bidodev** [comment]
Hey @gioboa that also works, I will start working on an MR for that.

**Comment by bidodev** [comment]
@gioboa I've set up a basic environment and written some initial tests, here: https://github.com/module-federation/vite/pull/120. Please let me know if I'm on the right track, so I can add more tests.

**Comment by gioboa** [comment]
That's great 🚀 @bidodev
