### ISSUE TITLE
💥 Unable to run Multi-Example

### ISSUE THREAD

**Issue by bidodev** [module-federation/vite#119]
Hello! :)
I’m trying to set up the e2e tests for the multi-example, but I can’t get it running.
I’m attempting to start it with pnpm run multi-example.

And I get some errors

<img width="883" alt="Screenshot 2024-09-28 at 22 15 36" src="https://github.com/user-attachments/assets/a525f9e1-0e19-423d-a797-4651aa5e2458">

node version: 20.9.0

Any ideas?

**Comment by gioboa** [comment]
Can you run run
`export NODE_OPTIONS=--openssl-legacy-provider` and then `pnpm run multi-example` pls?

**Comment by bidodev** [comment]
It worked, but then I had other problems with postcss, I found out in the end, that the issue was that my pnpm was the v8.15 after update to the last one, everything worked fine.
