### ISSUE TITLE
Dynamic remotes

### ISSUE THREAD

**Issue by tyler-mitchell** [module-federation/vite#12]
I was wondering if this plugin supports dynamic remote paths loaded from an api.

**Comment by gioboa** [comment]
Can you give me an example pls?

**Comment by tyler-mitchell** [comment]
@gioboa One example being: In your host app, you have a list of api remotes that are retrieved only at runtime

**Comment by gioboa** [comment]
I think it's possible to do it with a bit of code.

**Comment by gioboa** [comment]
```typescript
const response = await fetch('https://mocki.io/v1/1b1b8cc2-36b6-4652-bbd9-2f2b7a98388a');
const config = await response.json(); // { "remote" : "https://[your_remote_url]/remoteEntry.json"}
await initFederation(config);
```
I could call initFederation multiple times if you want to refetch the remotes configuration

**Comment by badasukerubin** [comment]
The perfect solution: https://github.com/module-federation/vite/issues/102#issuecomment-2370323651
E.g: https://github.com/module-federation/module-federation-examples/blob/master/dynamic-system-host/app1/src/App.js

**Comment by gerhardcit** [comment]
@gioboa , can you expand on `initFederation` please?
where does that come from?

We have the same requirement. multiple remote apps available, but based on a local runtime setting, we need to load the relevant one.

**Comment by gioboa** [comment]
@gerhardcit [This is](https://github.com/module-federation/vite/pull/148) a good starting point for dynamic remotes.
My answer was for the previous version of this plugin.

**Comment by gerhardcit** [comment]
Thanks @gioboa . Been digging a bit.
```typescript
import { loadRemote, registerRemotes, init } from '@module-federation/runtime';
```` 
opened up some opportunities for me.
Discovered that you can load remote apps at runtime without having the, defined in the vite.config.ts

There are two strategies.. Make sure all remote apps are structured like this in 
```typescript
plugins: [
 svelte(),
 federation({
      name: 'remote',
      filename: 'remoteEntry.js',
      exposes: {
        './remote-app': './src/index.ts',
      },
    }),
]
```

and then in the host app load them just be changing the url: 
however, registerRemotes can only be loaded once. so you have to do some internal state management 
```
init({
            name: 'host', // 🚨 Must match your host app's federation "name" in vite.config.ts
            remotes: [], // No pre-configured remotes (we load dynamically)
            shared: {
// unlike react, svelte apps reduces the requirement for shared libs since there is not real framework.. 
            },
        });

const remoteUrl: string = figureItOutFromRouteOrSomething();

registerRemotes([
            {
                name: 'remote',
                entry: remoteUrl,
                type: 'module',
            },
        ]);
``` 

is this an advisable way to go?

**Comment by gioboa** [comment]
a simple state to check if the remote is already registered is the cleanest solution IMHO
