### ISSUE TITLE
add Angular example

### ISSUE THREAD

**Issue by gioboa** [module-federation/vite#123]
The library has few examples and an Angular one will be amazing. (host and remote)

**Comment by moudgalya1223** [comment]
hello @gioboa  can you please assign this to me

**Comment by gioboa** [comment]
[This PR](https://github.com/module-federation/module-federation-examples/tree/master/module-federation-vite-angular) implements the solution. @moudgalya1223  you can add this example in this project and few e2e tests as well. Are you up for it?

**Comment by gioboa** [comment]
> isnt this one closed with the example you added in the module federation repo

Thanks @Seifenn
