### ISSUE TITLE
__mf__virtual seems to be an ES Module but shipped in a CommonJS package

### ISSUE THREAD

**Issue by TheSharpieOne** [module-federation/vite#128]
I am getting this when running vitest for testing:

```
SyntaxError: Unexpected token 'export'
 ❯ Object.<anonymous> ../node_modules/__mf__virtual/host__loadShare__react__loadShare__.js:7:27

Module /project/node_modules/__mf__virtual/host__mf_v__runtimeInit__mf_v__.js:7 seems to be an ES Module but shipped in a CommonJS package. You might want to create an issue to the package "__mf__virtual" asking them to ship the file in .mjs extension or add "type": "module" in their package.json.

As a temporary workaround you can try to inline the package by updating your config:

// vitest.config.js
export default {
  test: {
    server: {
      deps: {
        inline: [
          "__mf__virtual"
        ]
      }
    }
  }
}
```

**Comment by zhangHongEn** [comment]
I have not encountered this error, if necessary you can send a PR to automatically complete this setting in the `config hook`

**Comment by zhangHongEn** [comment]
Did the results from running npm run dev-vv and similar examples work correctly for you?

**Comment by TheSharpieOne** [comment]
running in dev and even production builds are fine. The issue only happens when running tests via vitest. vitest itself puts the blame on the package not correct indicating that it is ESM so I posted here instead of there. vitest's runtime is node rater than the browser so I think there is an issue requiring/importing the remote there.

**Comment by zhangHongEn** [comment]
I understand. Is setting deps.inline currently working as expected?
