### ISSUE TITLE
Allow to customize temporary folder or use vite temporary folder.

### ISSUE THREAD

**Issue by mshima** [module-federation/vite#137]
Temporary folder is hardcoded as `.__mf__temp` would me nice to allow to customize it.

**Comment by gioboa** [comment]
Yes, it's a nice improvement. Would you like to drop a PR for that?

**Comment by gioboa** [comment]
We can't move that directory because it's failing in Win environments 
[check this comment](https://github.com/module-federation/vite/issues/74#issuecomment-2324711903)
I close it.
