### ISSUE TITLE
When vite configures base, the plugin does not work properly.

### ISSUE THREAD

**Issue by He110te4m** [module-federation/vite#14]
More information can be found on [this issue](https://github.com/module-federation/vite/issues/10)

Problem recurrence can be viewed in [this project](https://github.com/He110te4m/module-federation-issue-10-reproduction-repo).

The initial determination is that the contents of dist do not contain the contents of base, causing the URL processed in server not to be added correctly.

The relevant code is on [this line](https://github.com/module-federation/vite/blob/main/src/index.ts#L51).

**Comment by He110te4m** [comment]
The substitution of [this line of code](https://github.com/module-federation/vite/blob/main/src/dev-externals-mixin.ts#L22) is also problematic

When base is configured, the imported path is replaced with `/base/@id/libraryName`.

The final replacement result is `/base${libraryName}`. For example: `/basereact` or `/basevue`

**Comment by He110te4m** [comment]
I've identified the problem and created a [PR](https://github.com/module-federation/vite/pull/15) to fix it.

If you have time please review the code and concurrency a new version.

**Comment by gioboa** [comment]
Yep, I will look into it. Thanks in advance
