### ISSUE TITLE
Examples for Dynamic Remotes

### ISSUE THREAD

**Issue by jofmi** [module-federation/vite#146]
Module Federation has a method to load dynamic remotes: https://module-federation.io/guide/basic/runtime.html 

The webpack plugin has the following application example: https://github.com/module-federation/module-federation-examples/tree/master/advanced-api/dynamic-remotes

It would be great if the examples here could be updated to demonstrate how to use this approach with vite.

**Comment by gioboa** [comment]
Thanks @jofmi for looking at this project.
[This is the file](https://github.com/module-federation/module-federation-examples/blob/master/advanced-api/dynamic-remotes/app1/src/App.js) to mimic with this package.

**Comment by judithhartmann** [comment]
I can set up the example!

**Comment by gioboa** [comment]
Let's use the multi-example because we have e2e test on it. we can create a different route to test this case. Thanks for your help @judithhartmann
