### ISSUE TITLE
examples: remove extra dependency

### ISSUE THREAD

**Issue by DmitryNakhimovich** [module-federation/vite#149]
I have a root application and 20+ mfe on webpack using mf 1.0. When migrating to vite and using this package, will old builds with webpack be supported or will it be necessary to rebuild all microfronts?
Is there a way to dodge webpack without rebuilding all microfronts?

**Comment by gioboa** [comment]
Hi, it's hard to say without trying. This is a very specific scenario. You can try locally and load into the vite mf v2 a mf v1.0 app.

**Comment by DmitryNakhimovich** [comment]
i'll play around with examples and give a feedback about my configurations.
But why you use https://github.com/module-federation/vite/blob/3815b436c142c144e5c41bfdd5b6638f783e800d/examples/vite-webpack-rspack/webpack/package.json#L42C5-L42C45 in dev dependency ? Is it required for build ?

**Comment by gioboa** [comment]
[This is](https://github.com/module-federation/vite/blob/main/examples/vite-webpack-rspack/webpack/package.json) the latest file. 
what package do you mean?

**Comment by DmitryNakhimovich** [comment]
"dependencies": {
    "react": "^18.3.1",
    "react-dom": "^18.3.1",
    **"@module-federation/vite": "workspace:*"**
  }
  
  "@module-federation/vite" not directly used in webpack config, but included in package.json (for webpack remote)

**Comment by gioboa** [comment]
Thanks, nice catch, [fixed](ef9bc5a5acec9792036b4373082928f7fbc9df59)
