### ISSUE TITLE
feat: add implementation option

### ISSUE THREAD

**Issue by gioboa** [module-federation/vite#157]
The implementation option is used to modify the actual bundler runtime version.

When working with Module Federation, the runtime is responsible for handling the loading and sharing of remote modules. By default, the bundler uses a specific version of the runtime that is compatible with its version. However, in some cases, you might need to use a different version of the runtime or a custom implementation.

By specifying the implementation option, you can provide a path to the desired runtime implementation. 

`This is particularly useful if you need to use features from a newer or older version of the runtime that are not available in the default version provided by the bundler.`

https://module-federation.io/configure/implementation.html

**Comment by RobinBomkamp** [comment]
Hey there, 
implementation has been added in version 1.1.7. Or am I wrong?
This issue can be closed.

**Comment by gioboa** [comment]
Yep, thanks @RobinBomkamp for your help
