### ISSUE TITLE
Unable to load remote unless CSP "unsafe-eval" CSP header is set

### ISSUE THREAD

**Issue by JamesMHenderson** [module-federation/vite#158]
Unable to load plugin or remotes as running eval is blocked by CSP

![image](https://github.com/user-attachments/assets/8adfc162-fcba-4742-b8be-db789688b00b)

![image](https://github.com/user-attachments/assets/f0acf649-b4b4-4be9-bfe9-c947383d00ac)

Similar issue seen with the Nextjs plugin https://github.com/module-federation/core/issues/2759

**Comment by gioboa** [comment]
Thanks for your feedback, we are using core so let's wait [this core PR](https://github.com/module-federation/core/pull/3067)

**Comment by fcano-ut** [comment]
Hi! The PR mentioned only fixes this inside the `nextjs-mf` package. I saw similar code in other packages but some where node-only, I decided to only fix what I had tested and validated before changing other packages. You are using the `core` package you mention?
You could try using `patch-package` to apply the fix, test it, and if it works submit a PR with a similar change 😃

**Comment by ScriptedAlchemy** [comment]
You can send a PR to my repo if you identify the function where evaluation causes the csp error, can just wrap it same as i do here. 

try {new Function()} catch { referenceThatBundlerMightChange()}

**Comment by JamesMHenderson** [comment]
Looks like this may have been fixed by https://github.com/module-federation/core/pull/3163
