### ISSUE TITLE
The entry point "react" cannot be marked as external

### ISSUE THREAD

**Issue by beeequeue** [module-federation/vite#16]
I'm trying to set up a minimal setup to test using this for work, but something seems wrong, as the dev server just crashes immediately as you load the site in the browser with the error `The entry point "react" cannot be marked as external`

Repro: https://github.com/BeeeQueue/repro-vite-mf-react

1. Install deps `pnpm i`
2. Run shell's dev server `mfs/shell: pnpm dev`
3. See error in console
4. Open dev server in browser and crash dev server

**Comment by Steelrover** [comment]
@BeeeQueue Hi! I've got the  same problem. Did you manage to solve it?

**Comment by gioboa** [comment]
The workaround is change your package.json and move react and react-dom in the devDeps
esBuild is throwing this error, I need to investigate

**Comment by seravifer** [comment]
Moving to devDeps seems to work but now when the remote loads, React throws errors:
`TypeError: Cannot read properties of null (reading 'useEffect'`

**Comment by gioboa** [comment]
I downgrade these versions:
```
"@module-federation/vite": "0.2.6",
"@softarc/native-federation": "1.1.2",
"@softarc/native-federation-esbuild": "1.1.1",
```
and it's working good. I will release a new version of `@module-federation/vite` with these dependencies.
@Steelrover is this workaround working for your project?

**Comment by cristiano-belloni** [comment]
> I downgrade these versions:
> 
> ```
> "@module-federation/vite": "0.2.6",
> "@softarc/native-federation": "1.1.2",
> "@softarc/native-federation-esbuild": "1.1.1",
> ```
> 
> and it's working good. I will release a new version of `@module-federation/vite` with these dependencies. @Steelrover is this workaround working for your project?

These versions give me a peer dependency failure. Why the solution to this is downgrading?

**Comment by hans-ts** [comment]
This is also an issue in the [React example](https://github.com/module-federation/module-federation-examples/tree/master/vite-react-microfrontends) linked from the README for this project.

**Comment by pedrocandidozup** [comment]
I have the same problem, any solutions for this?

**Comment by sedx** [comment]
Hi all! Just remove `react` plugin usage from vite config. It's solve error, but disable features of this plugin (such as HMR)

**Comment by cristiano-belloni** [comment]
Can we please mention in the README that this plugin is broken and doesn't work with with react? It will save a lot of time to all the developers who try to use it and find out it is, in fact, broken.

**Comment by gioboa** [comment]
@sedx Thanks for you suggestion
without the react plugin is working fine with all the latest deps (Vite 5, React 18.2.0 etc. etc.)
![image](https://github.com/module-federation/vite/assets/35845425/0d17e962-8995-4727-b2f9-4f8e834d0d41)

I'll look how to reintroduce the plugin and get rid of the error.

**Comment by gioboa** [comment]
I moved all the dependencies inside `devDependencies` object and we have no errors.
To avoid React duplication errors I read the React library from window.React in the Remote App
I updated this project here https://github.com/gioboa/react-microfrontend-demo
The famous error comes from this code https://github.com/evanw/esbuild/blob/70893e4d89bab1dbf2d512593f9e4d5bcb1f76bf/internal/bundler/bundler.go#L1813

**Comment by cristiano-belloni** [comment]
> To avoid React duplication errors I read the React library from window.React

This sounds everything but Module Federation 🤨

**Comment by gioboa** [comment]
@cristiano-belloni thanks for your feedback. Your suggestion could be a solution. In the newest versions of esbuild the internal implementation is changed, we are struggling with it. I would like to solve the problem because this package can help other developers. You can help as well with PRs if you want.

**Comment by cristiano-belloni** [comment]
@gioboa precisely - mark it as broken with React until it's fixed and link this issue. This way it will be immediately clear to developers. Trying to make it work with hacks like storing the React object in the global namespace makes things worse.

**Comment by gioboa** [comment]
Yup, that makes sense to me.
I think we can remove the react from the README and from the official examples.

**Comment by OscarLijoBusto** [comment]
+1

**Comment by gioboa** [comment]
We are working on a new version that will definitely solves this. @ScriptedAlchemy did a big step forward, he did the official esbuild adapter and the runtime loaders too.

**Comment by T-Klug** [comment]
+1 on a solution - removing the react plugin isn't an option for us, and downgrading feels incorrect. Looking forward to a new adapter and runtime loaders.

**Comment by JamesMHenderson** [comment]
@gioboa are there any timelines for the new version?

**Comment by gioboa** [comment]
We are working on a new version of this package in [this PR](https://github.com/module-federation/vite/pull/34) 
I'm closing this issue, if you want, you can try the new version and give us feedback. Thanks.
