### ISSUE TITLE
Cannot read properties of null (reading 'useMemo') in the latest version

### ISSUE THREAD

**Issue by badasukerubin** [module-federation/vite#161]
In version `1.0.0`, I'm able to implement mf in 2 react apps (host and remote) effectively. When building the remote in this version, I get a minimal number of outputs too. In a minified output;
```js
K=t.useMemo(function(){return Array(B).fill(null).map(function(Z,z){return{pageIndex:z,renderStatus:u.NotRenderedYet,visibility:x}})}

t=c(i)
...
var i=require$$0

...
require$$0=getAugmentedNamespace(z_mf_2_a__loadShare__react__loadShare__);
```

In version `1.1.3` on the other hand, I get the error: Cannot read properties of null (reading 'useMemo') plus PTSD from using https://github.com/originjs/vite-plugin-federation.
Sth like this in the build output.
```js
// assuming r is react 
r={current:null}

r.current.useMemo
```

**Comment by badasukerubin** [comment]
Switching to version 1.0.0 no longer works for me 😕

In my remote app, I have:

```tsx
import { ChakraProvider } from '@chakra-ui/react';
import React, { memo, StrictMode } from 'react';

export default memo(function app() {
  return (
  
    <ChakraProvider>
      <>Test</>
      <Test />
    </ChakraProvider>
  );
});

```

When I remove the `ChakraProvider`, it works. 
The `Test` component uses `memo` and `useRef`. Everything works with `memo` but fails when using `useRef`.

```ts
federation({
      name: 'react-pdf-viewer_pdf-viewer',
      filename: 'remoteEntry.js',
      getPublicPath: () => '/public/',
      exposes: {
        './app': './resources/js/app',
      },
      //   Commented or not, I still get the error
      //   shared: {
      //     react: { singleton: true },
      //     'react-dom': { singleton: true },
      //   },
    }),
```
This is my vite config above, do you think I'm missing a config/something? @gioboa

**Comment by badasukerubin** [comment]
I figured my issue out. In my vite config, I use `app.tsx` as an input (for https://github.com/laravel/vite-plugin). Exposing it seems to cause a problem and mess up the build.
Closing this.

**Comment by gioboa** [comment]
Thanks @badasukerubin for sharing the resolution. I'm glad you solved it
