### ISSUE TITLE
assets of dynamic remotes

### ISSUE THREAD

**Issue by Pong420** [module-federation/vite#171]
i have a dynamic remote using `vite`. it will be host by a domain different from the host. The following is the exposed component
```tsx
import heart from '@/assets/heart.png';

export default function Entry() {
  return (
    <div>
      <img src={heart} alt="" />
    </div>
  );
}
```

The output structure
```
dist/
├── assets
│   ├── ...
│   ├── heart-B7sPXKnk.png
│   ├── index-lGpEGtzZ.js
│   └── virtualExposes-DrUcl4CE.js
├── favicon.ico
├── index.html
└── remoteEntry.js
```
The value of heart will be `/assets/heart-B7sPXKnk.png`.  I can load can load the remote with `http://localhost:4173/remoteEntry.js`

How can i know the domain of `remoteEntry.js` is `http://localhost:4173/` or  any other domain ? any function/variable like `__webpack_public_path__`

**Comment by zhangHongEn** [comment]
`base` and `server.origin`

**Comment by Pong420** [comment]
Thanks, it missed the `server.origin` option

**Comment by gioboa** [comment]
Thanks @zhangHongEn for your support 
@Pong420 I am glad you sorted it out
