### ISSUE TITLE
Still unable to run host or remote using dev server if a base url is defined after #159 

### ISSUE THREAD

**Issue by Eliwang4264** [module-federation/vite#173]
I upgrade to v1.1.4 but I still can not  run the project if I set the base url
![image](https://github.com/user-attachments/assets/1970d686-cc3f-4ad9-b419-d921b03ae104)
![image](https://github.com/user-attachments/assets/a8f3c058-d53d-4946-a5cd-8b36b16781bb)

below is my vite config:

<img width="280" alt="WXWorkCapture_17304426861887" src="https://github.com/user-attachments/assets/c151b3b4-27bc-473e-9000-11523945dfa8">

**Comment by zhangHongEn** [comment]
If it is remote ,  set `server.origin`

**Comment by Eliwang4264** [comment]
I tried that before but sill have same issue
<img width="214" alt="WXWorkCapture_17304438445029" src="https://github.com/user-attachments/assets/bf39ed60-3f5f-40a9-83ea-f6652c8d4c34">

**Comment by zhangHongEn** [comment]
The [example](https://github.com/module-federation/vite/blob/4f43bc01f64bf12f13bb09cc3440a0a049cf6bf8/examples/vite-vite/vite-remote/vite.config.js#L16) works fine, so I’m not sure how to reproduce your scenario. Could you provide a reproducible example?

**Comment by Eliwang4264** [comment]
I have noticed an interesting phenomenon. If I set 'shared'(I shared the react and react-router-dom), the page will blank, but if I set 'shared' to an empty object, it will display normally.
You can try it out. If it still can't be reproduced, I will create a repo before this weekend

**Comment by Eliwang4264** [comment]
@zhangHongEn This [example](https://github.com/Eliwang4264/Mf2_vite_react_demo) can reproduce the issue, you can check the vite.config,js file, when set the shared the page will blank and if you comment shared and restart the project , it will display normal, but the console error always show.

**Comment by zhangHongEn** [comment]
@Eliwang4264 Are you using Windows?

**Comment by zhangHongEn** [comment]
![image](https://github.com/user-attachments/assets/bd9f4ae8-7223-4ca3-8d4f-89e1ca48642b)
I ran your example, and everything worked fine. I think it might be that Windows’ path rules weren’t handled properly

**Comment by zhangHongEn** [comment]
If you’re using Windows, I’ll find a device to fix it.

**Comment by Eliwang4264** [comment]
yep, I'm using windows

**Comment by Eliwang4264** [comment]
> ![image](https://private-user-images.githubusercontent.com/26006485/382570878-bd9f4ae8-7223-4ca3-8d4f-89e1ca48642b.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzA2Mzc0MzAsIm5iZiI6MTczMDYzNzEzMCwicGF0aCI6Ii8yNjAwNjQ4NS8zODI1NzA4NzgtYmQ5ZjRhZTgtNzIyMy00Y2EzLThkNGYtODllMWNhNDg2NDJiLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDExMDMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMTAzVDEyMzIxMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWM1OWFlYjJlMGM1N2UwNjc2NTFmYzlmMjMzMjAyNmYyZGNiMTVlMDZlZDU0OGQ4N2MzMDJiOWE4MzQ2YWY1ZTgmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.if92hs7nd1dZbPw33diBMuJG_shj8ue8SG9VhqNNVA8) I ran your example, and everything worked fine. I think it might be that Windows’ path rules weren’t handled properly

you don't comment the shared , right?

**Comment by zhangHongEn** [comment]
Alright, I’ll fix it today.

**Comment by zhangHongEn** [comment]
> > ![image](https://private-user-images.githubusercontent.com/26006485/382570878-bd9f4ae8-7223-4ca3-8d4f-89e1ca48642b.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzA2Mzc0MzAsIm5iZiI6MTczMDYzNzEzMCwicGF0aCI6Ii8yNjAwNjQ4NS8zODI1NzA4NzgtYmQ5ZjRhZTgtNzIyMy00Y2EzLThkNGYtODllMWNhNDg2NDJiLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDExMDMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMTAzVDEyMzIxMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWM1OWFlYjJlMGM1N2UwNjc2NTFmYzlmMjMzMjAyNmYyZGNiMTVlMDZlZDU0OGQ4N2MzMDJiOWE4MzQ2YWY1ZTgmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.if92hs7nd1dZbPw33diBMuJG_shj8ue8SG9VhqNNVA8) I ran your example, and everything worked fine. I think it might be that Windows’ path rules weren’t handled properly
> 
> you don't comment the shared , right?

yes

**Comment by Eliwang4264** [comment]
> If you’re using Windows, I’ll find a device to fix it.

I have tried two windows device, one is win10 and the other is win 11 vm and they both don't work properly
