### ISSUE TITLE
question: MF port configuration

### ISSUE THREAD

**Issue by danmorley** [module-federation/vite#177]
I get 404 errors as my host app is looking for the mf files on:
http://portal.local/@id/virtual:mf-REMOTE_ENTRY_ID

but they are being served here:
http://localhost:5173/application-ui/@id/virtual:mf-REMOTE_ENTRY_ID

How can I configure this to look in the right place?

**Comment by gioboa** [comment]
Hi, can you create a basic reproduction repository for this please?

**Comment by gioboa** [comment]
> I think possibly by changes in 1.14?

I don't think so. I'm glad that is working for you with the latest release.
