### ISSUE TITLE
Issue loading vite remote in webpack host

### ISSUE THREAD

**Issue by m-arav** [module-federation/vite#188]
Hi,

I am trying to load a vite remote using this plugin in a webpack host using the MF2 webpack [plugin](https://module-federation.io/guide/basic/webpack.html)

Trying to do so causes this error
`Uncaught SyntaxError: Cannot use import statement outside a module (at remoteEntry.js:2:1)`
followed by a federation runtime error. My guess is the federation runtime error might be occurring because the initial error is preventing the remoteEntry.js file from being loaded.

Any idea on what I am doing wrong?

My configs are as follows:
vite remote:
```
federation({
      name: 'vite_remote',
      filename: "remoteEntry.js",
      exposes: {
        './App': './src/bootstrap',
      },
      shared: ["react", "react-dom"],
    }),
```

webpack host:

```
new ModuleFederationPlugin({
      name: 'webpack',
      remotes: {
        viteremote: 'vite_remote@http://localhost:4173/remoteEntry.js',
      },
      shared: {
        ...deps,
        react: {
          singleton: true,
        },
        'react-dom': {
          singleton: true,
        },
      },
    })
```

### screenshot
![Screenshot 2024-11-21 at 10 28 45 PM](https://github.com/user-attachments/assets/65050b75-3c6a-47c5-8dba-0f0bc151933d)

**Comment by zhangHongEn** [comment]
webpack.config.js

{
  remoteType: "module"
}

**Comment by m-arav** [comment]
Adding `remoteType: "module"` produces this error:
`ERROR in external "vite_remote@http://localhost:4173/remoteEntry.js"
The target environment doesn't support dynamic import() syntax so it's not possible to use external type 'module' within a script`

As a separate question: Is it possible to to apply `remoteType` per remote? Thinking of a scenario where the webpack host has a vite remote on MF2 and other webpack remotes on MF1

**Comment by zhangHongEn** [comment]
https://module-federation.io/configure/manifest.html

If webpack remoteType doesn’t work, you can use json instead.

**Comment by m-arav** [comment]
Thank you. Switching to use `manifest: true` in the Vite remote config worked for me.

Vite remote config
```
federation({
      name: 'vite_remote',
      manifest: true,
      exposes: {
        './App': './src/App',
      },
      shared: ["react", "react-dom"],
    }),
```

Webpack host:
```
new ModuleFederationPlugin({
      name: 'webpack',
      remotes: {
        viteremote: 'vite_remote@http://localhost:4173/mf-manifest.json',
      },
      shared: {
        ...deps,
        react: {
          singleton: true,
        },
        'react-dom': {
          singleton: true,
        },
      },
    }),
```

**Comment by b-sw** [comment]
@m-arav Did that work for you out of the box? I'm wrapping my head around the same problem and when I use mf-manifest.json, in the host app I get
```
Uncaught SyntaxError: Unexpected token ':' (at mf-manifest.json:1:6)
```
because I think it's being fetched as a _script_ instead json.

**Comment by m-arav** [comment]
> [@m-arav](https://github.com/m-arav) Did that work for you out of the box? I'm wrapping my head around the same problem and when I use mf-manifest.json, in the host app I get
> 
> ```
> Uncaught SyntaxError: Unexpected token ':' (at mf-manifest.json:1:6)
> ```
> 
> because I think it's being fetched as a _script_ instead json.

@b-sw Yes, changing to manifest json was all that was needed in my case.

Not sure if this helps but I have seen `Uncaught SyntaxError: Unexpected token ':'` once, the response that caused this was not json but an HTML 404 page due to the way my CDN was setup.

It should not be fetched as a script, This discussion touches on that aspect: https://github.com/module-federation/core/discussions/3282

**Comment by b-sw** [comment]
Thank you @m-arav for a quick response! FYI I overcame these difficulties with an inline import (fetch also works for manifest) in the host app webpack configuration of the module-federation plugin (since simply using manifest instead is not working for me):
```typescript
            new ModuleFederationPlugin({
                name: someName
                filename: someFile.js,
                remotes: {
                    '@my/remote': `promise import('http://localhost:1234/my_remote.js')
                         .then(module => ({
                         get: request => module.get(request),
                         init: arg => module.init(arg)
                     }))`,
                },
            }),
```

**Comment by DevJoaoLopes** [comment]
@m-arav I'm trying to do the same thing that worked for you, but with no results. Maybe I'm doing something wrong... can you help me?

<img width="801" height="996" alt="Image" src="https://github.com/user-attachments/assets/2b05a7ae-0a85-46fe-8f9b-8e5507f1257c" />

https://github.com/DevJoaoLopes/react-webpack-host-vite-remote

**Comment by m-arav** [comment]
@DevJoaoLopes Try removing the [filename: 'remoteEntry.js'](https://github.com/DevJoaoLopes/react-webpack-host-vite-remote/blob/main/remote/vite.config.ts#L10) in your vite remote config. `manifest: true` will default to using a filename `mf-manifest.json`

P.S: Make sure the you can access the manifest file location defined in the [host](https://github.com/DevJoaoLopes/react-webpack-host-vite-remote/blob/main/host/webpack.config.js#L18C25-L18C63) from your browser by going to `http://localhost:3001/mf-manifest.json`, If it loads then module federation plugin will also be able to access it, if it does not load then you have figure out where `vite preview` is serving those files at.

**Comment by m-arav** [comment]
@DevJoaoLopes I don't have my previous examples anymore. It was very similar to the repo you shared.

The manifest files looks right. It seems your remoteEntry file is located at `http://localhost:3001/assets/remoteEntry-Hp1xEPDp.js`.

1. Can you access this file?
2. What does your console error say? The previous console error screenshot had mf looking for the file at `http://localhost:3001/remoteEntry.js` which threw a `404`.


Note sure if this helps, I remember vite HMD causing issues with module federation. I had to do a `vite build --base=http://localhost:3001` to get mf to work. The base argument was help with some path issues.

**Comment by DevJoaoLopes** [comment]
Thanks for your support, @m-arav .

I managed to resolve the issue by making some adjustments to the project and inserting a [promise import](https://github.com/DevJoaoLopes/react-webpack-host-vite-remote/blob/be1970fa52aab3f7da5475a961d2aa5c384f16ee/host/webpack.config.js#L18) as @b-sw  mentioned above.
