### ISSUE TITLE
Adding hostInit does not work if there is no html file (SvelteKit)

### ISSUE THREAD

**Issue by RobinBomkamp** [module-federation/vite#189]
If you want to use module-federation/vite in combination with SvelteKit. The hostInit file does not get included in the generated output. The file is compiled, but the reference is missing.

It used to work in version 1.1.3 of this package. 

In version 1.1.4 there was a fix for the issue #167. This caused the problem.
After the fix the hostInit will be referenced directly in the html <head> element in a script tag. Therefore, the plugin check every file ending with '.html' (see [pluginAddEntry.ts](https://github.com/module-federation/vite/blob/main/src/plugins/pluginAddEntry.ts#L117))

SvelteKit does not generate any HTML files. The <head> element is generated on the server side due to ssr. A template of the base html file is part of the generated internal.js file.

```typescript
...addEntry({
      entryName: 'hostInit',
      entryPath: getHostAutoInitPath(),
      inject: 'html',
    }),
``` 

The `inject: 'html'` causes the problem. If you are setting this value to 'entry' or simply remove it the hostInit will be referenced as before the issue #167.

Should this field be made configurable? Or can it be injected as an entry for svelte kit projects as before?

**Comment by zhangHongEn** [comment]
I noticed another issue remains unresolved. Can version 1.1.3 be successfully used in SvelteKit?

**Comment by zhangHongEn** [comment]
If the SSR environment can be detected, use inject: 'entry'.

**Comment by RobinBomkamp** [comment]
Issue can be closed :)
It is part of version 1.1.8.

**Comment by gioboa** [comment]
Thanks @RobinBomkamp
