### ISSUE TITLE
Question : it supports singleton?

### ISSUE THREAD

**Issue by cjz9032** [module-federation/vite#19]
I believe so many libraries do not support singleton by itself, while we need to ensure the isolation between the remotes and host.
if MF supports singleton will be good news.

**Comment by gioboa** [comment]
Yep, the library supports singleton. Can you describe me a real scenario pls?

**Comment by thibaultvdb-hexagon** [comment]
An example would be to run multiple React apps on the same page in a horizontal split architecture :)

**Comment by gioboa** [comment]
yep, It's working. you can check [this repo](https://github.com/gioboa/react-microfrontends-spotify)
