### ISSUE TITLE
Error sharing "vue-demi" library, unable to export "createApp"

### ISSUE THREAD

**Issue by kehuay** [module-federation/vite#190]
## Reproduction
https://github.com/kehuay/module-federation-share-vue_demi.git

## Problem
- console
![console](https://github.com/user-attachments/assets/e6a221e4-9896-41fe-a6d4-ac3cb40ce4dd)

- bundler
![bundler](https://github.com/user-attachments/assets/5e1f5c5e-ba02-4e1b-b411-b6195ddf8d42)

Include require in the package file, and there is no export of vue related apis

**Comment by zhangHongEn** [comment]
```js
optimizeDeps: {
    exclude: ["vue-demi"]
  },
  ```
  remove exclude

**Comment by kehuay** [comment]
@zhangHongEn 

When sharing vue and Vue-demi at the same time, running Vue-demi in main.ts and App.vue to import createApp and ref failed

## Reproduction
https://github.com/kehuay/module-federation-share-vue_demi.git

Reproduced in apps/remote

## main.ts
```ts
import { createApp } from 'vue-demi'
import './style.css'
import App from './App.vue'

createApp(App).mount('#app')
```

## module federation config
```ts
import { defineConfig } from 'vite'
import vue from '@vitejs/plugin-vue'
import { federation } from '@module-federation/vite'

// https://vite.dev/config/
export default defineConfig({
  optimizeDeps: {
    // exclude: ["vue-demi"]
  },
  plugins: [
    vue(),
    federation({
      name: 'remote',
      // manifest: true,
      filename: 'remoteEntry.js',
      shared: {
        'vue-demi': {
          singleton: true,
        },
        'vue': {
          singleton: true
        }
      },
      shareStrategy: 'loaded-first',
      exposes: {
        "./App": "./src/App.vue"
      }
    })
  ],
  server: {
    port: 5001
  }
})
```

## Errors
![image](https://github.com/user-attachments/assets/16acc18b-1786-4169-838f-b6eab116f804)

**Comment by zhangHongEn** [comment]
This issue is a bit tricky. Since vue-demi transparently passes through all of Vue’s properties, you can currently opt not to share it and instead only share Vue.

```js
import { defineConfig } from 'vite'
import vue from '@vitejs/plugin-vue'
import { federation } from '@module-federation/vite'

// https://vite.dev/config/
export default defineConfig({
  optimizeDeps: {
    // exclude: ["vue-demi"]
  },
  resolve: {
    alias: {
      "vue-demi": "vue-demi/lib/index.cjs"
    }
  },
  plugins: [
    vue(),
    federation({
      name: "host",
      filename: 'remoteEntry.json',
      shared: {
        "vue": {
          singleton: true
        }
      },
      shareStrategy: 'loaded-first'
    })
  ],
  server: {
    port: 5000
  }
})
```

**Comment by zhangHongEn** [comment]
Dynamic modules conflict with Vite’s pre-build mechanism, and only Vite 6, with support for dynamic ES modules, can perfectly resolve this issue.

**Comment by kehuay** [comment]
https://github.com/module-federation/vite/issues/190#issuecomment-2497043250

Effective, thank you, 有效的，谢谢。

https://github.com/module-federation/vite/issues/190#issuecomment-2497077729

When is vite6 expected to be available? Production environment

**Comment by zhangHongEn** [comment]
我没有vite6支持module-federation的准确时间, 预计是今年q4, 但可能会更慢, 但如果2025年迟迟不支持的话 我可能会考虑去协助

**Comment by zhangHongEn** [comment]
shared: {
        "vue": {
          singleton: false,
          version: "3.2.0",
          requiredVersion: "~3.2.0"
        }
      },

**Comment by kehuay** [comment]
> 我没有vite6支持module-federation的准确时间, 预计是今年q4, 但可能会更慢, 但如果2025年迟迟不支持的话 我可能会考虑去协助

那@module-federation/vite的mf-manifest.json什么时候可以与rsbuild的module-federation插件生成的mf-manifest.json文件功能相同，我尝试在@module-federation/vite使用mf-manifest.json，mf-manifest.json文件内容缺少很多功能

**Comment by kehuay** [comment]
> 缺少什么内容, 没有发现缺少内容, 我一直有在正常用

## vite.config.ts
```ts
import { defineConfig } from 'vite'
import vue from '@vitejs/plugin-vue'
import { federation } from '@module-federation/vite'

// https://vite.dev/config/
export default defineConfig({
  optimizeDeps: {
    // exclude: ["vue-demi"],
    include: ['faim > qrcode', 'faim > sweetalert2', 'faim > upng-js'],
  },
  resolve: {
    alias: {
      "vue-demi": "vue-demi/lib/index.cjs"
    }
  },
  plugins: [
    vue(),
    federation({
      name: 'remote',
      manifest: true,
      // filename: 'remoteEntry.js',
      shared: {
        // 'vue-demi': {
        //   singleton: true,
        // },
        'vue': {
          singleton: true
        }
      },
      shareStrategy: 'loaded-first',
      exposes: {
        "./App": "./src/App.vue"
      }
    })
  ],
  server: {
    port: 5001
  }
})
```

## mf-manifest.json
![image](https://github.com/user-attachments/assets/ed2b0bc4-0a90-4baf-a36f-9031e0803fea)

**Comment by zhangHongEn** [comment]
dev mode无需填充预加载内容, build正常

**Comment by kehuay** [comment]
> dev mode无需填充预加载内容, build正常

那在dev mode下联调需要怎么解决，我在尝试dev mode使用mf-manifest.json时报错
![image](https://github.com/user-attachments/assets/62fd2cf1-93ff-48d2-bdbb-a00895b5c97a)

## dynmic init
```ts
import { createApp } from 'vue'
import './style.css'
import App from './App.vue'
import { init } from '@module-federation/enhanced/runtime'
import { createPinia } from 'pinia'

init({
    name: 'host',
    remotes: [
        {
            name: 'remote',
            // entry: 'http://localhost:5001/remoteEntry.js',
            // type: 'module'
            entry: 'http://localhost:5001/mf-manifest.json'
        }
    ]
})

const piniaApp = createPinia()

createApp(App).use(piniaApp).mount('#app')
```

## use
```ts
const RemoteApp = defineAsyncComponent(() => loadRemote("remote/App"))
```

**Comment by zhangHongEn** [comment]
设置 `server.origin`

**Comment by kehuay** [comment]
> 设置 `server.origin`

Ok，

再请教一个问题，怎么在module-federation/vite里使用unocss，我的remote中导出的组件使用了unocss，主host也使用了unocss，但host导入的remote组件unocss并未生效

**Comment by gioboa** [comment]
Hi @kehuay, can I suggest you to join our [Discord Server](https://discord.gg/UJQXwNKZ) to chat about this extra questions? The issue problem is solved so I close the issue. Thanks for your understanding.
