### ISSUE TITLE
Cannot serve application on host 127.0.0.1 with shared options

### ISSUE THREAD

**Issue by nicotu01** [module-federation/vite#194]
Step to reproduce : 

1. create a simple vue project with vite.
2. configure vite server.host to `127.0.0.1` 
3. configure federation and share `vue`
4. serve the application and open `http://127.0.0.1` : the application does not work

Here my vite config:
```
import { defineConfig } from "vite";
import vue from "@vitejs/plugin-vue";
import { federation } from "@module-federation/vite";

// https://vite.dev/config/
export default defineConfig({
  plugins: [
    vue(),
    federation({ name: "host", shared: ["vue"] }),
  ],
});

```

**Comment by gioboa** [comment]
Hi @nicotu01
Can you share your errors too? Thanks

**Comment by nicotu01** [comment]
There's are NO error ;-). 
Only a white page.  

I find how to resolve : 

Use the server host : 
- In https://github.com/module-federation/vite/blob/main/src/plugins/pluginProxyRemoteEntry.ts#L60

```
          const {init} = await import("//${viteConfig.server?.host || 'localhost'}:${viteConfig.server?.port}${viteConfig.base + options.filename}")
```

- In https://github.com/module-federation/vite/blob/main/src/plugins/pluginAddEntry.ts#L44

```
          const { host, port } = server.config.server;
          fetch(`http://${host}:${port}${devEntryPath}`).catch((e) => {});

```

**Comment by gioboa** [comment]
Nice @nicotu01 May I ask you to create a PR for that?

**Comment by nicotu01** [comment]
Yes, of course. 
But I can't create branch. Do I need permissions ?

**Comment by gioboa** [comment]
Sending a Pull Request
- Fork the repository into your own account.
- Clone your forked repository.
- In your forked repository, create a new branch: git checkout -b my-branch main.
- Make your changes/fixes.
- Run pnpm fmt to lint the code.
- Push your branch to GitHub: git push origin my-branch
- In GitHub, send a pull request to module-federation/vite

**Comment by nicotu01** [comment]
Hi @gioboa 
Here is the PR : https://github.com/module-federation/vite/pull/196

But Playwright tests are broken.
I'm not that it is due to my code. I've the same error on main branch.

How can we progress on the subject ?
