### ISSUE TITLE
App not works on custom local domain with shared dependencies

### ISSUE THREAD

**Issue by tduforet** [module-federation/vite#199]
The dev server is configured with host: '0.0.0.0', when I launch the server, I can access to the page on localhost but not on my custom local domain (it's just a blank page) configured in /etc/hosts.
It worked with federation 1.1.6 but not with 1.1.7.

Here is a example. You just have to configured a custom local domain in your /etc/hosts by example (127.0.0.1   dev.local) and access the app with the custom domain.

https://github.com/tduforet/federation-local-hostname

**Comment by gioboa** [comment]
Hi @tduforet thanks
I close this one because it's duplicate of #194

**Comment by tduforet** [comment]
Hello I tried with the last version and I still have the problem

**Comment by gioboa** [comment]
Can you share with us your errors @tduforet please?
cc @nicotu01

**Comment by gioboa** [comment]
@tduforet Can you try this fix #215 and double check if it's solving things for you?
The easiest way to do that is using [pnpm patch](https://pnpm.io/it/cli/patch)

**Comment by tduforet** [comment]
Hello @gioboa, I didn't use pnpm patch, but I set a npm link with the local dependency with the fix and It seems to be ok.
Thanks @nicotu01

**Comment by gioboa** [comment]
Thanks @tduforet for your help 💪
