### ISSUE TITLE
Vite 6.0 is not supported, and a compilation error is reported

### ISSUE THREAD

**Issue by gongph** [module-federation/vite#201]
env:

- vite6.0

**Comment by zhangHongEn** [comment]
I tried it and didn’t encounter any issues. Could you provide an example to reproduce the problem?

**Comment by zhangHongEn** [comment]
I encountered an issue with top-level await in build mode. Let me take a look.

**Comment by gongph** [comment]
Right, that's the build issue: `await isn't allowed in non-async`

**Comment by ErickDevv** [comment]
### **Same problem with Vite 6.**

#### I init a project with Vite 6 and Module Federation. When I run `npm run build` I get the following error message:

_**NOTE: It is important to mention that I tested with Bun and Nodejs.**_

```shell
error during build:
[commonjs] node_modules/__mf__virtual/remote__loadShare__react__loadShare__.js (14:31): await isn't allowed in non-async function
file: C:...//node_modules/react-dom/cjs/react-dom.production.min.js:14:31

12:       requiredVersion: "^18.3.1"
13:     }}}))
14:     const exportModule = await res.then(factory => factory())
                                   ^
15:     module.exports = exportModule
```

Replace `...` with the path to the project.

My `package.json` file is:


```json
{
  "name": "remote",
  "private": true,
  "version": "0.0.0",
  "type": "module",
  "scripts": {
    "dev": "vite --port 4174",
    "build": "tsc && vite build",
    "preview": "bun run build && vite preview --port 4174"
  },
  "dependencies": {
    "@module-federation/vite": "^1.1.7",
    "install": "^0.13.0",
    "react": "^18.3.1",
    "react-dom": "^18.3.1"
  },
  "devDependencies": {
    "@eslint/js": "^9.15.0",
    "@types/react": "^18.3.12",
    "@types/react-dom": "^18.3.1",
    "@vitejs/plugin-react": "^4.3.4",
    "eslint": "^9.15.0",
    "eslint-plugin-react-hooks": "^5.0.0",
    "eslint-plugin-react-refresh": "^0.4.14",
    "globals": "^15.12.0",
    "typescript": "~5.6.2",
    "typescript-eslint": "^8.15.0",
    "vite": "^6.0.1"
  }
}
```

**Comment by gongph** [comment]
Hi @ErickDevv 
use `vite@5.4.0` is build ok

**Comment by RobinBomkamp** [comment]
Shouldn't vite 5.4.0 then be included as a peerDependency?

**Comment by gioboa** [comment]
Yep @RobinBomkamp, we need a way to say "it's working with v5 at the moment". feel free to drop a PR for that please.

**Comment by ScriptedAlchemy** [comment]
> Right, that's the build issue: `await isn't allowed in non-async`

can it be set to async mode in vite 6?
