### ISSUE TITLE
"module-federation/vite" does not work effectively when using the "vite-plugin-top-level-await" plugin

### ISSUE THREAD

**Issue by kehuay** [module-federation/vite#205]
The development environment works, but does not work after packaging

## Reproduction

https://github.com/[kehuay/mf-top-await](https://github.com/kehuay/mf-top-await)

## error

![image](https://github.com/user-attachments/assets/f39d2e46-fdc8-415d-b5aa-568614eac122)

**Comment by gongph** [comment]
How many versions of Vite is?

You don't need a 'top-await' to use the `build: { ... }` config item. Also, there is a problem with the vite6.0+ build

**Comment by kehuay** [comment]
vite 5，The project relies on "vite-plugin-top-level-await" and packaging failed when I used "build{}"

**Comment by gongph** [comment]
> vite 5，The project relies on "vite-plugin-top-level-await" and packaging failed when I used "build{}"

If you're using the build config item, you don't need the top-await plugin
