### ISSUE TITLE
Catch failed modules fallback

### ISSUE THREAD

**Issue by Innders** [module-federation/vite#207]
We are trying to use MF to dynamically load extra features (addons) into our core application. This works great when the addons `remoteEntry.js` file is present but we can't always guarantee that it will be there.

Is there a graceful way to handle the failed loading of these missing modules without the app crashing?

Ideally the app wouldn't crash and the imports for the modules would just be `undefined`, that way the host application can handle it and provide it's own fallback.

This might be a stupid idea so please suggest something different!

```
Uncaught TypeError: Failed to fetch dynamically imported module: http://localhost:3000/addons/{addon_name}/remoteEntry.js
```

**Comment by gioboa** [comment]
Hi @Innders thanks for your feedback.
Is there a way to manage this errors with module federation webpack/rspack?
If yes we should definitely follow the same path.

**Comment by Innders** [comment]
> manage this errors with module federation webpack/rspack

Well i'm not sure if handling the error is the right approach anyway. Maybe the remote modules should be dynamically imported instead of through the vite.config.ts file?

**Comment by yuvalkarif** [comment]
@Innders, You may also consider using the plugin system to write your own custom logic which proved to be very helpful to my usecases.
See the retry-plugin for inspiration
https://module-federation.io/plugin/plugins/retry-plugin.html
https://github.com/module-federation/core/blob/main/packages/retry-plugin/src/index.ts

**Comment by Innders** [comment]
@yuvalkarif That's pretty cool and resolves my initial issue, thanks!

In the end I ended up going for a dynamic loading strategy using [federation runtime](https://module-federation.io/guide/basic/runtime.html).

Register all remotes in `index.tsx`
``` tsx
import { registerRemotes } from '@module-federation/enhanced/runtime'

registerRemotes([
  {
    name: 'remote',
    alias: 'remote',
    entry: `http://localhost:5001/remoteEntry.js?date=${new Date().toISOString()}`, // date string prevents caching
    type: 'module',
  },
])
```

Dynamically load each module on demand providing a fallback, this also helps set the type of the module (which I haven't figured out yet how to do).

`useLoadRemote.ts` hook to be reused around the app.
```ts
import { loadRemote } from '@module-federation/enhanced/runtime'
import { useEffect, useRef, useState } from 'react'
import { RemoteType } from './registerAddonRemotes'

interface Props<T> {
  remote: RemoteType
  module: string
  fallback: T
}

const useLoadRemote = <T>({ remote, module, fallback }: Props<T>) => {
  const [isLoaded, setIsLoaded] = useState(false)
  const loadedRemote = useRef<T>(fallback)

  useEffect(() => {
    if (isLoaded) return
    loadRemote<{ default: T }>(`${remote}/${module}`, {
      from: 'runtime',
    })
      .then((remote) => {
        setIsLoaded(true)
        if (remote) loadedRemote.current = remote.default
      })
      .catch((e) => {
        console.error('error loading remote', remote, module, e)
      })
  }, [isLoaded])

  return loadedRemote.current
}

export default useLoadRemote
```

Use the hook.
```tsx
  // load slicer remote config
  const config = useLoadRemote({
    remote: 'slicer',
    module: 'config',
    fallback: { progress: { fields: ['hierarchy'] } },
  })
```

Please feel free to critique/correct this but it is working pretty well right now.

**Comment by yuvalkarif** [comment]
Looks good, the `vite` library uses the `runtime` to do all of its magic behind the scenes, so using the runtime just gives you more flexibility and it seems to be working great for you.

Plugins can be also added to the runtime instance, so if you want you can consider them to append the date query params for all of your remotes as an example, but that's kind of out of scope for this repository.

**Comment by gioboa** [comment]
Thanks for sharing @Innders @yuvalkarif
