### ISSUE TITLE
TypeError (analogjs): Cannot read properties of undefined (reading 'push') when launching shell

### ISSUE THREAD

**Issue by Seifenn** [module-federation/vite#210]
When i launch my application using module federation i get the following error

TypeError: Cannot read properties of undefined (reading 'push')

When i enter inside the code of the federation module i noticed that this part is causing the error inside index.cjs

```javascript

     name: 'watchLocalSharedImportMap',
    apply: 'serve',
    config: function config(_config3) {
      _config3.optimizeDeps = defu.defu(_config3.optimizeDeps, {
        exclude: [getLocalSharedImportMapPath()]
      });
      _config3.server = defu.defu(_config3.server, {
        watch: {
          ignored: []
        }
      });
      var watch = _config3.server.watch;
      watch.ignored = [].concat(watch.ignored);
      watch.ignored.push("!**" + getLocalSharedImportMapPath() + "**");
    }
  }];
```
when i log the value of the watch variable i get false but it should be   

```javascript
watch: {
          ignored: []
        }
```
So i initialized it to this value and its working i can run the shell and the remote loaded in the shell

```javascript

       name: 'watchLocalSharedImportMap',
    apply: 'serve',
    config: function config(_config3) {
      _config3.optimizeDeps = defu.defu(_config3.optimizeDeps, {
        exclude: [getLocalSharedImportMapPath()]
      });
      _config3.server = defu.defu(_config3.server, {
        watch: {
          ignored: []
        }
      });
      var watch = _config3.server.watch;
      console.log(watch)
      watch =  {
        ignored: []
      }
      watch.ignored = [].concat(watch.ignored);
      watch.ignored.push("!**" + getLocalSharedImportMapPath() + "**");
    }
  }];
}
```
here the value of watch inside _config3.server is false and the code should change this value

```javascript
 _config3.server = defu.defu(_config3.server, {
        watch: {
          ignored: []
        }
      });
```

 But its not overriding the value of watch . I dont know if this error is happening for a specific case in my project  since i'm using analog js as a host or it should be corrected when the value is false it should be initialized if the defu function does not update the value my project can be found on github [vite-module-federation-angular-test](https://github.com/Seifenn/vite-module-federation-angular-test).

**Comment by gioboa** [comment]
Hi @Seifenn I didn't look into the code yet 
What's the difference between your example and the [official one](https://github.com/module-federation/module-federation-examples/tree/master/module-federation-vite-angular)?

**Comment by Seifenn** [comment]
The difference is that i'm using an analogjs project as a host not only bare angular. The problem appeared when using analog since i have another example with angular vite that is working correctly.
