### ISSUE TITLE
vite build fail,when use vite-plugin-top-level-await

### ISSUE THREAD

**Issue by menghany** [module-federation/vite#214]
When building my project, I want to ensure compatibility with older browsers, so I modified the build configuration in the demo. However, after completing the build, it fails to run.
![image](https://github.com/user-attachments/assets/e6798c54-c624-4069-b401-c38a1ce25f86)
my build command success
`cd /examples/vite-vite/vite-remote`
`pnpm run build`
When i run 
`pnpm run preview`
is error
![image](https://github.com/user-attachments/assets/31a88292-b77e-4052-a811-ec1fde796a7f)
![image](https://github.com/user-attachments/assets/04d4556b-3460-40ac-8450-ddb961094561)

**Comment by gioboa** [comment]
Hi @menghany,
I reproduced the problem and hacked the compiled like this

from 
```
i()
```

to 
```
setTimeout(() => i(), 0);
```

and now it's working. So I'm woundering if it's a specific problem of `vite-plugin-top-level-await` :thinking:

**Comment by deizianens** [comment]
I have the exact same error on my app, also using `vite-plugin-top-level-await ` and running `vite preview `command. Did you find any solution to this?

**Comment by gioboa** [comment]
You can use the build -> target Vite config.
Which browser do you need to support?

**Comment by deizianens** [comment]
@gioboa The most used browsers: chrome, safari, edge...
Think I can use build target: esnext, right?
