### ISSUE TITLE
angular: TypeError: Cannot read properties of undefined (reading 'indexOf') When Launching Applicaiton After Upgrading Module Federation Version in Angular Project from 1.1.2 to 1.1.9

### ISSUE THREAD

**Issue by Seifenn** [module-federation/vite#219]
### Description

I have an Angular project using Vite and Module Federation. The project was working correctly with version `1.1.2`, but after upgrading to the latest version `1.1.9`, I am encountering the following error when launching the application:

TypeError: Cannot read properties of undefined (reading 'indexOf')`

### Screenshot

![image](https://github.com/user-attachments/assets/5223102d-3c97-4114-a85d-cef683ee67f3)
![image](https://github.com/user-attachments/assets/b6b10961-d31e-4c00-a6ba-70a56029c09c)

I tried upgrading version by version, and the error first appeared in `v1.1.6`, which includes the update of `@module-federation/runtime`. This update seems to be the cause of the issue.

### Steps to Reproduce

1. Upgrade `module-federation` from version `1.1.2` to `1.1.9` (or any version starting from `1.1.6`).
2. Launch the application.
3. The error will occur in the console as mentioned above.

### Expected Behavior

The remote should work as expected without throwing any errors.

### Actual Behavior

The application throws a `TypeError: Cannot read properties of undefined (reading 'indexOf')`.

### Repository

The repo can be found here:  
[vite-module-federation-angular-test](https://github.com/Seifenn/vite-module-federation-angular-test/tree/upgrade-module-federation-vite-version)

### Additional Information

It seems the update of `@module-federation/runtime` in version `1.1.6` might be related to the error. If you need any more information or assistance in reproducing the issue, feel free to ask!

**Comment by gioboa** [comment]
Hi @Seifenn this errors is from `supports-color` :thinking: 
So I think someone is using this.
You can use `pnpm list --recursive --json` in your project to extract the [dep tree](https://pnpm.io/cli/list)

**Comment by 2heal1** [comment]
It should read isomorphic-rslog browser field instead of main while the target is web/browser .

**Comment by 2heal1** [comment]
I see the `vite.config` set [resolve.mainFields](https://vite.dev/config/shared-options.html#resolve-mainfields) as `['module']` , so it not handle the browser , you can adjust the config field

**Comment by Seifenn** [comment]
I already have the resolve.mainField set as ['module'] in my vite.config. This error appeared after the upgrade of module federation version. i dont know if this happened to anyone else or maybe if there is a relation with angular since there are no other complaints from users with other frameworks.

**Comment by gioboa** [comment]
> if there is a relation with angular since there are no other complaints from users with other frameworks

It's only with Angular / Analog

**Comment by Seifenn** [comment]
@gioboa I was trying to test the old version of https://github.com/gioboa/vite-module-federation to  make it work with the latest version of the angular architects native federation since it implemented ssr support and there are problems with angular and ssr with this package of module federation . Since i want to integrate the angular architects plugin with vite because i want to use module federation with vite and angular and ssr with analog and i found that this was the approach you adopted first by integrating the angular-architects package with vite . Can you explain to me why you stopped ? and if its possible to make it work with the latest version of the angular architects package and analog using your old plugin.

**Comment by gioboa** [comment]
There has been poor package adoption in the past with native federation (based on npm downloads), few issues with esbuild (after a specific release) even with React and Vue. So @zhangHongEn dropped the first PR to update the library and create a common configuration between Webpack, Rspack, Vite. Then, after a few weeks of development, he created a common layer to mix and match things with other bundlers. We released v1 and immediately received great feedback from the community, adoption started to grow.
The advantage of having a common configuration and adoption leads us to continue with module federation

> Since i want to integrate the angular architects plugin with vite because i want to use module federation with vite and angular and ssr

I think we can improve things and support SSR frameworks in the future.
Btw we are looking for contributors so you can help us too if you want.

**Comment by gioboa** [comment]
I updated the demo with the latest version.
I fixed the issue by removing
```
resolve: {
  mainFields: ['module'],
},
```
Now it's working fine in dev end preview mode.
Thanks @2heal1 for your hint about node vs browser files.
