### ISSUE TITLE
Deploying to production

### ISSUE THREAD

**Issue by GabrielSuttner** [module-federation/vite#221]
I'm working on a project that is 2 Vue-3 applications. The host app has the navigation, a search bar, and some other frontend stuff and the remote app has customer orders and profile settings. Everything is working in development. But I can't figure out how to deploy the code to production. If I run "npm run build" in the host repository, the remote app isn't pulled in. Does anyone know a resource to help with deploying? 

Host vite.config.ts
```

import { defineConfig, loadEnv } from 'vite';
import vue from '@vitejs/plugin-vue';
import { federation } from '@module-federation/vite';
import topLevelAwait from 'vite-plugin-top-level-await';

const version = '0.1.22';

export default defineConfig(({ mode }) => {
  const env = loadEnv(mode, process.cwd(), '');

  const siteId = 'test';

  return {
    build: {
      rollupOptions: {
        output: {
          entryFileNames: `[name].${version}.js`,
          chunkFileNames: `[name].${version}.js`,
          assetFileNames: `[name].${version}.[ext]`
        }
      }
    },
    plugins: [
      vue(),
      federation({
        name: 'app',
        filename: 'app.js',
        remotes: {
          customerProfile: {
            type: 'module',
            name: 'customerProfile',
            entryGlobalName: 'customerProfile',
            entry: 'http://localhost:2000/remoteEntry.js'
          }
        },
        shared: ['vue', 'vue-router']
      })
    ],
    resolve: {},
       headers: {
        'Access-Control-Allow-Origin': '*',
        'Access-Control-Allow-Methods': 'GET, POST, PUT, DELETE, OPTIONS',
        'Access-Control-Allow-Headers':
          'Origin, X-Requested-With, Content-Type, Accept, Authorization'
      }
    }
  };
});
```

Remote vite.config.ts
```

import { defineConfig, loadEnv } from 'vite';
import topLevelAwait from 'vite-plugin-top-level-await';
import { federation } from '@module-federation/vite';
import vue from '@vitejs/plugin-vue';

const version = '0.1.22';

export default defineConfig(({ mode }) => {
  const env = loadEnv(mode, process.cwd(), '');

  return {
    plugins: [
      vue(),
      federation({
        filename: 'remoteEntry.js',
        name: 'customerProfile',
        exposes: {
          './export-app': './src/export-app.ts'
        },
        shared: ['vue', 'vue-router'],
        manifest: true
      })
    ],
    build: {
      rollupOptions: {
        output: {
          entryFileNames: `[name].${version}.js`,
          chunkFileNames: `[name].${version}.js`,
          assetFileNames: `[name].${version}.[ext]`
        }
      }
    },

    resolve: {},
    server: {
      port: 2000
    },

    define: {
    }
  };
});

```

**Comment by gioboa** [comment]
Hi @GabrielSuttner can you share the error too pls?

**Comment by GabrielSuttner** [comment]
I don't get any error when I run the build command, but I do get an error if I move the contents of dist to where they are served on Nginx. So before I implemented MF, I was serving the files on my NGINX server without any issue. Now, if I build the project and replace my pre-MF files with post-MF files, I am getting this error. 

Uncaught TypeError: i is not a function
    at hostInit.0.1.22.js:1:119

Where if you go to the file, this is what is in the file. 

```
import {init as i} from "./app.js";
import "./app__mf_v__runtimeInit__mf_v__.0.1.22.js";
import "./virtualExposes.0.1.22.js";
i();
```

I assume that I just don't understand the proper build sequence for MF projects as I have never done one before. 

My main question is what is the build process for module-federation with vite. I.e., do you just run "npm run build" in the host app? In my app that would run ""vite build --emptyOutDir --outDir dist." Or do you run "npm run build" in each application and then combine them somehow?

**Comment by gioboa** [comment]
Can you replace `i()` with `setTimeout(i, 0)` and test this solution please?

**Comment by GabrielSuttner** [comment]
I made the change and now there is no error but nothing is showing on the screen. So the webpage is just white.

**Comment by gioboa** [comment]
> I made the change and now there is no error but nothing is showing on the screen. So the webpage is just white.

Did you start host and remote in preview mode?

**Comment by GabrielSuttner** [comment]
The above screenshot is both of them in preview mode.

**Comment by GabrielSuttner** [comment]
I can add you to the repo so you can have a better view.

**Comment by GabrielSuttner** [comment]
If I add 

setTimeout(() => {
  i();
}, 10);

then it works.
