### ISSUE TITLE
When using Vite 6.0 + @module-federation/vite 1.2.0,the application fails to build and run

### ISSUE THREAD

**Issue by menghany** [module-federation/vite#227]
main branch vite6: https://github.com/menghany/mf-vite-report，
v5 branch vite5: https://github.com/menghany/mf-vite-report/tree/v5
This is my simple reproducible project,
`cd remote-react && pnpm i && pnpm run dev`
`cd host-vue3 && pnpm i && pnpm run dev`
The page does not render. Additionally, when I run pnpm run build for both projects,  I encounter the following error:  factory is not function.
However, when I use Vite 5.4.11 and @module-federation/vite 1.1.9, everything works correctly.

**Comment by gioboa** [comment]
Hi @menghany I see, can you host your application on GitHub please?

**Comment by menghany** [comment]
> Hi @menghany I see, can you host your application on GitHub please?

Of course,https://github.com/menghany/mf-vite-report

**Comment by menghany** [comment]
Hi,@gioboa @zhangHongEn  Thank you for your contribution!could you please release a new version? I need it. ”

**Comment by gioboa** [comment]
cc @ScriptedAlchemy

**Comment by gioboa** [comment]
[1.2.1](https://www.npmjs.com/package/@module-federation/vite/v/1.2.1) is available.
