### ISSUE TITLE
Support to expose sharable components to non-vite based projects built on webpack 5.

### ISSUE THREAD

**Issue by codeandgyan** [module-federation/vite#23]
This module federation plugin works well when **both** remote and host apps are built using **vite**.
However, I didn't find a way to expose sharable components using module federation to non-vite applications and vice-a-versa.

Here are some scenarios:
Scenario 1:
A: I have a vite based react application that uses this vite module federation plugin to expose some sharable components.

B: I have a non-vite based react application that is built using webpack 5 (also supports module federation). This application needs to consume a shareable component built in A. How do I do that?

C: I have an angularjs app which wants to consume A. How is it possible?

Scenario 2:
A: I have a vite based react application that should consume a UI component built by another application B or C as explained below.

B: This is a non-vite based react application that uses webpack 5 which exposes some sharable components using module federation.

C: I have an angularjs app which has exposed shareable components using module federation.

----
Essentially,  I want the module-federation should be framework agnostic.

Request you to please guide me with building above capabilities. 

Appreciate your efforts in building this library.

**Comment by gioboa** [comment]
Hi, I understand your needs.
can you share a basic repo example pls?

**Comment by codeandgyan** [comment]
Well, I don't have a sample app build as of now. I will share with you once I build one.
Thanks for your prompt reply.

**Comment by gioboa** [comment]
Yep, thanks. A basic example is the easiest way to figure out a solution.

**Comment by kaidjohnson** [comment]
I have created a [basic example ](https://github.com/kaidjohnson/federation-interop) demonstrating the issue with interoperability between webpack Module Federation and vite Native Federation, both with a vite host and webpack remote as well as a webpack host with a vite remote. The issues are slightly different, depending on which side each stack is on.

**Comment by Cafezinho** [comment]
Anyone figured out a way to handle remoteEntry.json with a Module Federation host?

**Comment by gioboa** [comment]
We are working on a new version that will definitely solves this. @ScriptedAlchemy did a big step forward, he did the official esbuild adapter and the runtime loaders too.

**Comment by renansoares** [comment]
@gioboa @ScriptedAlchemy any news on this? an esbuild adapter to support webpack + native federation? I'm also happy to happy if there's an official issue or something like that.

**Comment by gioboa** [comment]
We are working on a new version of this package in [this PR](https://github.com/module-federation/vite/pull/34) 
I'm closing this issue, if you want, you can try the new version and give us feedback. Thanks.
