### ISSUE TITLE
Lost tailwind css style of remote app when call from host at production mode

### ISSUE THREAD

**Issue by lecong** [module-federation/vite#25]
Hi,

I use Tailwind CSS for a remote app. In production mode, the CSS styles of the remote app are lost if the remote app is accessed from the host. On the other hand, if the remote app is accessed directly, the CSS styles of the remote app are not lost.

At dev mode, CSS styles of the remote app are not lost.

How to resolve it.

**Comment by gioboa** [comment]
Hi, the CSS of your host app is not including the remote Tailwind classes I guess. Did you check it out?

**Comment by gioboa** [comment]
This issue is stale, so I'm closing this for now.
Feel free to re-open it if it's still valid. Thanks.

**Comment by bbchuoo** [comment]
@lecong 

Hi, I have the same problem. Did you find a solution? I would like to know how to solve it. Thank you.

**Comment by vnmadhusudhan2** [comment]
in my case i dont want to include Tailwind in the host. in this case how css will get applied to remote app.
