### ISSUE TITLE
How to troubleshoot build errors

### ISSUE THREAD

**Issue by jonaskello** [module-federation/vite#3]
I think this plugin looks very promising :-). However when I tried to use it on an larger existing code base I run into a number of errors and I'm not sure how to proceed with the troubleshooting. The code builds fine with regular vite.

This plugin uses the `@softarc/native-federation` which seems to do a lot of the work. I would like to dig into the code of that but I cannot find it anywhere. Do you know if that package is closed source? I did not find a license file in the installed directory for it.

Here is an example of the errors I run into:

```
 INFO  Preparing shared package styled-components
✘ [ERROR] Could not resolve "stream"

    node_modules/.tmp/_styled_components_dist_styled_components.esm.js:2684:29:
      2684 │       var _require = require('stream');
           ╵                              ~~~~~~~~

  The package "stream" wasn't found on the file system but is built into node. Are you trying to
  bundle for node? You can use "platform: 'node'" to do that, which will remove this error.

 ERR!  Error bundling npm package styled-components
 ERR!  Build failed with 1 error:
 ERR!  node_modules/.tmp/_styled_components_dist_styled_components.esm.js:2684:29: ERROR: Could not resolve "stream"
 ERR!  For more information, run in verbose mode
 ```

I think somehow I need to augment the build process, but without the source for the build adapter stuff it is hard to know how to do it. Maybe it is related to `fileReplacements` but I'm not sure how to figure out how they work without digging into the missing source code.

**Comment by jonaskello** [comment]
After some digging I think I found the source for `@softarc/native-federation`:

https://github.com/angular-architects/module-federation-plugin/tree/main/libs/native-federation-core

**Comment by jonaskello** [comment]
I made some progress. I had left out `shared` in `withNativeFederation` which I thought meant share nothing, but appearently it means share a lot of things :-) So it tried to build separate files for everything, leading to a lot of errors. Once I realized that I could start with `shared: {}` and move from there.

**Comment by nuxzero** [comment]
I also got build errors from the `@softarc/native-federation` as well.

```
error during build:
TypeError [PLUGIN_ERROR]: The "path" argument must be of type string. Received an instance of Object
    at new NodeError (node:internal/errors:393:5)
    at validateString (node:internal/validators:163:11)
    at Object.join (node:path:1176:7)
    at _getPackageInfo (my-app/node_modules/.pnpm/registry.npmjs.org+@softarc+native-federation@1.1.1/node_modules/@softarc/native-federation/src/lib/utils/package-info.js:176:30)
    at getPackageInfo (my-app/node_modules/.pnpm/registry.npmjs.org+@softarc+native-federation@1.1.1/node_modules/@softarc/native-federation/src/lib/utils/package-info.js:41:22)
    at my-app/node_modules/.pnpm/registry.npmjs.org+@softarc+native-federation@1.1.1/node_modules/@softarc/native-federation/src/lib/core/bundle-shared.js:20:69
    at Array.map (<anonymous>)
    at my-app/node_modules/.pnpm/registry.npmjs.org+@softarc+native-federation@1.1.1/node_modules/@softarc/native-federation/src/lib/core/bundle-shared.js:20:14
    at Generator.next (<anonymous>)
    at my-app/node_modules/.pnpm/tslib@2.5.0/node_modules/tslib/tslib.js:167:75
 ELIFECYCLE  Command failed with exit code 1.
 ```

**Comment by jonaskello** [comment]
I currently have trouble with version `1.1.1` of `@softarc/native-federation`, it creates empty react bundles. It does however work with `1.1.0`.  In the git repo above I cannot find any changes for `1.1.1` so it is hard to troubleshoot. I guess it is better to wait a bit to use native-federation until the home for the `@softarc/native-federation` code has become clear so we can troubleshoot and help out with PRs.

**Comment by nuxzero** [comment]
@jonaskello The error is gone after change to version `1.1.0`. Thank you so much. :)

**Comment by gioboa** [comment]
Can we close this issue?

**Comment by jonaskello** [comment]
@gioboa The troubles I had was really related to `@softarc/native-federation` and not this package, but I could not find the source code repo for that, perhaps do you know where it is?

In the end since the code was not available, I ended up re-implementing a native federation like solution from scratch myself so yes it can be closed. But it would be nice to have a common implementation of native-federation available to collaborate on.
