### ISSUE TITLE
New-config Main branch and npm

### ISSUE THREAD

**Issue by husayt** [module-federation/vite#32]
Hi @gioboa, new-config branch is in good state and library is working for me. 

The problem is that since it is not the main branch it is not published in npm and using libary from github via ` "@module-federation/vite": "github:module-federation/vite#new-config"` doesn;t work as lib folder is not included. That stops many people from being able to try try and give feedback.

Would be great to have it in npm even as a beta version to be able to get more feedback and get edge cases covered.

I for instance have some issues and not sure if it is me or library. Having more people would help to get to root of those issues quickly.

Thanks

This is what I mean:
https://www.npmjs.com/package/@module-federation/vite?activeTab=versions

PS. if you think it is yet early to switch to this branch, at least can you please publish this branch to npm as beta.  See [here](https://stackoverflow.com/questions/39548780/how-do-i-npm-publish-a-unstable-or-develop-package)

**Comment by gioboa** [comment]
I can cut a new 1.0 alpha release from the `new-config` branch> 
does it work for you?

**Comment by husayt** [comment]
Yes, as long as it  can be used from npm.

**Comment by gioboa** [comment]
I added pkg-pr-new for that, but I am waiting for a module-federation approval.
So we'll be able to have a new installable package after each commit. 💪

**Comment by husayt** [comment]
Excellent, once merged I will add few more examples.

**Comment by husayt** [comment]
Closing this one. As we have alpha bundles in npm

**Comment by gioboa** [comment]
Thanks @husayt
