### ISSUE TITLE
`Failed to parse URL ` in latest

### ISSUE THREAD

**Issue by husayt** [module-federation/vite#36]
Latest is broken.

I pulled  latest from git and get this error when trying to get example running. A build from Sunday doesn't have that issue

```
Forced re-optimization of dependencies
node:internal/deps/undici/undici:12618
    Error.captureStackTrace(err, this);
          ^

TypeError: Failed to parse URL from http://localhost:5173C:\code\temp\mf-vite\node_modules\.pnpm\an-empty-js-file@1.0.0\node_modules\an-empty-js-file\empty.js?__mf__wrapRemoteEntry__
    at node:internal/deps/undici/undici:12618:11
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5) {
  [cause]: TypeError: Invalid URL
      at new URL (node:internal/url:796:36)
      at new Request (node:internal/deps/undici/undici:6108:25)
      at fetch (node:internal/deps/undici/undici:10396:25)
      at fetch (node:internal/deps/undici/undici:12617:10)
      at fetch (node:internal/bootstrap/web/exposed-window-or-worker:79:16)
      at Server.<anonymous> (C:\code\temp\mf-vite\lib\index.cjs:230:9)
      at Object.onceWrapper (node:events:632:28)
      at Server.emit (node:events:530:35)
      at emitListeningNT (node:net:1931:10)
      at process.processTicksAndRejections (node:internal/process/task_queues:81:21) {
    code: 'ERR_INVALID_URL',
    input: 'http://localhost:5173C:\\code\\temp\\mf-vite\\node_modules\\.pnpm\\an-empty-js-file@1.0.0\\node_modules\\an-empty-js-file\\empty.js?__mf__wrapRemoteEntry__'
  }
}

Node.js v20.12.2
 ELIFECYCLE  Command failed with exit code 1.
```

**Comment by husayt** [comment]
> Also running build in latest gives this warning:
> 
> ```
> Entry module "src/index.ts" is using named and default exports together. Consumers of your bundle will have to use `vite["default"]` to access the default export, which may not be what you want. Use `output.exports: "named"` to disable this warning
> Entry module "src/index.ts" is using named and default exports together. Consumers of your bundle will have to use `vite["default"]` to access the default export, which may not be what you want. Use `output.exports: "named"` to disable this warning
> No name was provided for external module '@rollup/pluginutils' in output.globals – guessing 'pluginutils' 
> Creating a browser bundle that depends on Node.js built-in modules ("path"). You might need to include https://github.com/FredKSchott/rollup-plugin-polyfill-node
> Build "@module-federation/vite" to lib:
>       6.03 kB: index.cjs.gz
>       5.38 kB: index.cjs.br
>       4.97 kB: index.modern.js.gz
>       4.43 kB: index.modern.js.br
>       5.79 kB: index.esm.js.gz
>       5.16 kB: index.esm.js.br
> ```

This not related to the original error of the issue, but still causing a warning and better be handled.

This is the cause:

https://github.com/module-federation/vite/commit/694a27de143d3591a2fee82342b732d0f563d840#r145077564

**Comment by zhangHongEn** [comment]
> @gioboa @zhangHongEn do you get examples working for you?

@husayt  I added remoteEntry filename support for hash yesterday, it seems incompatible with Windows

**Comment by husayt** [comment]
@zhangHongEn let's use https://unjs.io/packages/pathe instead of path.js that will take care of most of issues for us.

**Comment by zhangHongEn** [comment]
I will support dynamic import tonight, and I will fix it later. But I don't have a Windows device, so it's very difficult to deal with such problems.
The problem with windows appears in this file
https://github.com/module-federation/vite/blob/new-config/src/utils/vitePluginAddEntry.ts

**Comment by zhangHongEn** [comment]
> @zhangHongEn let's use https://unjs.io/packages/pathe instead of path.js that will take care of most of issues for us.

I'll try it tonight

**Comment by zhangHongEn** [comment]
@husayt https://github.com/module-federation/vite/blob/5fccb3c4115941f218542b95f8cee551fa668d4b/src/utils/vitePluginAddEntry.ts#L39C1-L40C1
Try changing this line of code to see if it works. I need to wait a few hours before I can start.
``` js
entryPath.replace(/.+?\:([/\\])[/\\]?/, '$1').replace(/\\\\?/g, '/')
```

**Comment by zhangHongEn** [comment]
@husayt fixed

**Comment by husayt** [comment]
Yes, @zhangHongEn that has been fixed in the latest. Thank you
