### ISSUE TITLE
wrong React in remote subdependencies (require(react))

### ISSUE THREAD

**Issue by husayt** [module-federation/vite#39]
I am not sure if this is issue with this library,  vite  or runtime module federation. But It works with webpack module federation.

So basically react in vite remote app works fine, react components render normally. But when I try to use Ag-grid-react I get infamous `Invalid hook call.` error. 
```TypeError: Cannot read properties of null (reading 'useRef')
    at Object.useRef (chunk-EFTEWGEA.js:1074:29)
    at AgGridReactUi (ag-grid-react.js:13873:36)
    at renderWithHooks (react-dom.development.js:16305:18)
    at mountIndeterminateComponent (react-dom.development.js:20074:13)
    at beginWork (react-dom.development.js:21587:16)
    at HTMLUnknownElement.callCallback2 (react-dom.development.js:4164:14)
    at Object.invokeGuardedCallbackDev (react-dom.development.js:4213:16)
    at invokeGuardedCallback (react-dom.development.js:4277:31)
    at beginWork$1 (react-dom.development.js:27451:7)
    at performUnitOfWork (react-dom.development.js:26557:12)
 ```

Seems the issue with right version react obtained via require inside ag-grid-react (CJS library):
```
    var react_1 = __importStar(require_react());
``` 
@zhangHongEn you just fixed an issue for dynamic imports, maybe we also need fix for `require`

**Comment by zhangHongEn** [comment]
@husayt Good issue, I will fix it at noon

**Comment by husayt** [comment]
Also similar error when I use MUI (Material UI)

```
TypeError: Cannot read properties of null (reading 'useContext')
    at Object.useContext (chunk-EFTEWGEA.js:1062:29)
    at useTheme (chunk-JKYVMHHX.js:3290:32)
    at useTheme2 (chunk-JKYVMHHX.js:3298:10)
    at useThemeProps (chunk-JKYVMHHX.js:3839:15)
    at useThemeProps2 (chunk-JKYVMHHX.js:6377:10)
    at Paper2 (@mui_material.js:1304:17)
    at renderWithHooks (react-dom.development.js:16305:18)
    at updateForwardRef (react-dom.development.js:19226:20)
    at beginWork (react-dom.development.js:21636:16)
    at beginWork$1 (react-dom.development.js:27426:14)
```

**Comment by husayt** [comment]
> @husayt Good issue, I will fix it at noon

I have other issues two, but this is the biggest and most serious issue affecting anyone who would try do any realistic use with 3rd party libraries.

**Comment by zhangHongEn** [comment]
> > @husayt Good issue, I will fix it at noon
> 
> I have other issues too, but this is the biggest and most serious issue affecting anyone who would try do any realistic use with 3rd party libraries.

Yes, this is a very important bug, but I didn't have time to look at it until 7 hours later.

**Comment by husayt** [comment]
> Yes, this is a very important bug, but I didn't have time to look at it until 7 hours later.

that is fine, i posted some other issues as well. I just wanted to say that this one is the most pressing one among them.

**Comment by gioboa** [comment]
@zhangHongEn you are doing great, take your time to avoid burnouts :rocket:

**Comment by zhangHongEn** [comment]
Vite pre-built subdependencies cannot be proxied in the usual way. I have found a solution, but I have been too busy recently and may need to wait for two days.

**Comment by husayt** [comment]
I made a simple repro to  test this case. Will try to commit that later. But gist of it I added another remote with
with these dependencies
```
  "dependencies": {
    "@module-federation/vite": "workspace:*",
    "react": "^18.2.0",
    "react-dom": "^18.2.0",
    "vue": "^3.4.29",
    "vue-router": "^4.4.0",
    "ag-grid-community": "^30.2.0",
    "ag-grid-react": "^30.2.0"
  },
```
and `AgGridDemo.jsx`
```
import 'ag-grid-community/styles/ag-grid.css';
import 'ag-grid-community/styles/ag-theme-alpine.css';
import { AgGridReact } from 'ag-grid-react';
import { useState } from 'react';


export const AgGridDemo = ({  }) => {
  const [rowData] = useState([
    { make: 'Toyota', model: 'Celica', price: 35000 },
    { make: 'Ford', model: 'Mondeo', price: 32000 },
    { make: 'Porsche', model: 'Boxter', price: 72000 },
  ]);

  const [columnDefs] = useState([{ field: 'make' }, { field: 'model' }, { field: 'price' }]);

  return (
    <div className="App">
      <div style={{ display: 'flex', flexDirection: 'row' }}>
        <div
          id="grid1"
          className="ag-theme-alpine"
          style={{ height: 400, width: 600, margin: '20px' }}
        >
          <AgGridReact rowData={rowData} columnDefs={columnDefs}></AgGridReact>
        </div>
        <div
          id="grid2"
          className="ag-theme-alpine"
          style={{ height: 400, width: 600, margin: '20px' }}
        >
          <AgGridReact rowData={rowData} columnDefs={columnDefs}></AgGridReact>
        </div>
      </div>
    </div>
  );
};
 ```
 
 When running this remote on its own all works fine.

But when I try to run it from another host via MF I get the same error
```
Object.useRef (chunk-D5PPDA7K.js:1074:29)
    at AgGridReactUi (ag-grid-react.js:69725:36)
    at renderWithHooks (chunk-BISVECJP.js:11548:26)
    at mountIndeterminateComponent (chunk-BISVECJP.js:14926:21)
    at beginWork (chunk-BISVECJP.js:15914:22)
    at HTMLUnknownElement.callCallback2 (chunk-BISVECJP.js:3674:22)
    at Object.invokeGuardedCallbackDev (chunk-BISVECJP.js:3699:24)
    at invokeGuardedCallback (chunk-BISVECJP.js:3733:39)
    at beginWork$1 (chunk-BISVECJP.js:19765:15)
    at performUnitOfWork (chunk-BISVECJP.js:19198:20)
```

**Comment by husayt** [comment]
> [zhangHongEn@06dc35d](https://github.com/zhangHongEn/vite/commit/06dc35dcde589bc4fce02b4714ea7db907823f73) All that remains is to make this step automatic.

This looks very promising. Tried to test the proposed solution on the example above. Seems I am missing something, so I have to wait for proper solution. Very excited to finally get this working. Thank you

**Comment by zhangHongEn** [comment]
@husayt Finally finished, thank you for finding this problem, I will test it again and issue a PR tomorrow night

https://github.com/zhangHongEn/vite/commit/d79fe1859c274ce08f55510497fcf8af5b085aa9

**Comment by zhangHongEn** [comment]
compeleted

**Comment by husayt** [comment]
Thank you @zhangHongEn . I tried to run latest and examples, but I get "Please call init first" error on both host and remote examples

![image](https://github.com/user-attachments/assets/2729c15c-0a69-4d20-b8eb-678bb0d4932a)
