### ISSUE TITLE
default exports from pathed dependencies

### ISSUE THREAD

**Issue by husayt** [module-federation/vite#41]
Until [this fix](https://github.com/module-federation/vite/commit/7c3ba59d2581ee713b02aee85f5854dbe8e0e114) i had to add `.default`
to use any default exports from shared libraries.
```
import Lib from "sharedLib";
```

[this fix](https://github.com/module-federation/vite/commit/7c3ba59d2581ee713b02aee85f5854dbe8e0e114) had resolved it.

But if my shared library is like this
```
  "@material-ui/core/Grid": { singleton: true },
 ```  
and I import it like this
```
import Grid from "@material-ui/core/Grid";
```
then i still have to add `.default` to get default out
```
 return (
 <Grid.default> </Grid.default>
 return (
```

**Comment by zhangHongEn** [comment]
The need for explicit .default is a bug

**Comment by zhangHongEn** [comment]
I understand that what you shared is not a complete npm package. I have never done this before. This scenario really needs to be enhanced.
