### ISSUE TITLE
No loader is configured for ".scss"  files

### ISSUE THREAD

**Issue by iigormr** [module-federation/vite#43]
I'm new to using federation and I'm having doubts and problems when configuring it to use .scss with vite.

Are you having the same problems? Could you help me?

Here are the versions I'm using:
"@module-federation/vite": "^0.2.8",
"@softarc/native-federation": "^2.0.10",
"@softarc/native-federation-esbuild": "^2.0.10",

"vite": "^5.0.8",
"vite-plugin-sass": "^0.1.0"

![2024-08-09 11_56_54-](https://github.com/user-attachments/assets/a7a0e7bc-75c6-49be-87fa-a8bbcb500798)
![2024-08-09 11_57_09-](https://github.com/user-attachments/assets/45851bfe-f1e2-4097-9fdc-3aac5caee7ef)
![2024-08-09 11_57_33-](https://github.com/user-attachments/assets/697c0897-331f-4305-84fc-0a2704401835)

**Comment by zhangHongEn** [comment]
You can try [@module-federation/vite@next](https://www.npmjs.com/package/@module-federation/vite/v/1.0.0-alpha-4a73cd4)

**Comment by gioboa** [comment]
Thanks @husayt
