### ISSUE TITLE
How to get assets/images from Remote

### ISSUE THREAD

**Issue by husayt** [module-federation/vite#52]
I have made a few examples with different features. One key thing I couldn't get working is to get assets or images from remotes loaded in the host.

@zhangHongEn maybe you have an idea how to do it? Or is it maybe not supported yet?
```[tasklist]
### Tasks
```

**Comment by husayt** [comment]
Here is a reproduction in examples:

![image](https://github.com/user-attachments/assets/1015cc15-a62d-4f15-b7fd-8bc037654199)

When run from host the dark background image is not loaded. (you can see the difference)

**Comment by husayt** [comment]
@zhangHongEn you mentioned this on vite board, but I have webpack remote with images working fine Vite MF host.

**Comment by zhangHongEn** [comment]
When vite dev mode is used as remote, base will be invalid and vite will always use "/"
![image](https://github.com/user-attachments/assets/5f733551-2ed9-4efc-b400-fcb0ab61a347)
![image](https://github.com/user-attachments/assets/1ebb0a47-15c8-4d0a-a13c-905c2a747c50)

**Comment by zhangHongEn** [comment]
It should use localhost:5176/src/assets/viteback.png

**Comment by husayt** [comment]
Can we do any override on our side? Like find a replace  `/src/assets/viteback.png` with `http://localhost:5176/src/assets/viteback.png`

**Comment by zhangHongEn** [comment]
Yes. We may need to find a solution ourselves.

**Comment by zhangHongEn** [comment]
I haven't had time to look at it yet. The "base" failure range may be relatively large. I'm not sure what other resources besides pictures have the same problem.

**Comment by husayt** [comment]
> http://localhost:5176/src/assets/viteback.png is the correct value, not /src/assets/viteback.png

@zhangHongEn  To come back to this point, where you suggest to use hardcoded full (absolute) url. You see, it is often not possible, as you might have different environments (dev, uat, local, prod) each with different urls. So full url can only be known at runtime

**Comment by hi-ogawa** [comment]
Hey, thanks for the effort of bringing module federation on Vite!
I noticed you were commenting on Vite relative base issue 17482, but I'm not sure if this feature is the one you need, so just I started to check your plugin.

Have you look into using `server.origin` option? https://vitejs.dev/config/server-options.html#server-origin
The documentation about this option is very terse (it's only briefly mentioned in for backend integration https://vitejs.dev/guide/backend-integration.html#backend-integration), but it looks like this might be a key to force absolute url for the assets to be served from remote app. 

For example, after updating remote side vite config with `server.origin`, I can see `backend-image` seems to be fixed.

```ts
//// in examples/vite-vite/vite-remote/vite.config.js

export default defineConfig({
  server: {
    open: true,
    port: 5176,
    origin: 'http://localhost:5176'
  },
  // base: 'http://localhost:5176',
  ...
```

<details><summary>Reveal screenshot</summary>

![image](https://github.com/user-attachments/assets/2a855838-3f2c-4135-8d1b-c1251bb1777a)

</details>

**Comment by zhangHongEn** [comment]
@hi-ogawa Awesome, that should solve the problem perfectly. Thank you.

**Comment by zhangHongEn** [comment]
@husayt  If server.origin is effective, we can add it to README or set it automatically through the plugin

**Comment by zhangHongEn** [comment]
> but also base value is often runtime defined. is there a way to get it from environment variables. So that means it will not be hardcoded, but defined by the environment

In build mode, import.meta.env.BASE_URL can be used
https://vitejs.dev/gui/build.html#public-base-path

**Comment by husayt** [comment]
@hi-ogawa this is great. Thank you

@zhangHongEn  it will be  very helpful for us to come with recommended settings for base path and server origin path. I think we can omit base path altogether


PS. the correct URL above is https://vitejs.dev/guide/build.html#public-base-path.

**Comment by husayt** [comment]
Also @zhangHongEn , what I noticed is really interesting

- when we run remote in prod mode without `base` setting css doesn't load
- when we run remote in dev mode without `server.origin` setting images don't load

so currently we need to set 'base` path in prod build and `server.origin` in dev mode for remote to work.

What is interesting:

1. without `server.origin` in prod mode images load
2. without `base` path in dev mode css just work.

So it seems by providing automatic `server.origin` value in prod and automatic `base` path value in dev, we can have app working pretty much without the need for either  `server.origin` or  `base` settings to be provided

**Comment by zhangHongEn** [comment]
> @hi-ogawa this is great. Thank you
> 
> @zhangHongEn it will be very helpful for us to come with recommended settings for base path and server origin path. I think we can omit base path altogether. You suggested setting origin path automatically. That will be really interesting, but how would it work?
> 
> PS. the correct URL above is https://vitejs.dev/guide/build.html#public-base-path.

We should be able to automatically set server.origin to localhost:{port}, or we can indicate in the README that server.origin needs to be set.

**Comment by badasukerubin** [comment]
Your solution worked for me @husayt

**Comment by jfconde** [comment]
@husayt this fixed my issue. Thank you so much!
