### ISSUE TITLE
Can't use styled-components as shared

### ISSUE THREAD

**Issue by smelukov** [module-federation/vite#56]
@zhangHongEn
Bug reproduction is [here](https://github.com/smelukov/vite/tree/repro) (repro-branch)

Just start vite-host and vite-remote

```
App1.jsx:4 Uncaught TypeError: styled is not a function
    at App1.jsx:4:16
```

If styled-components is not shared, then all is fine

**Comment by zhangHongEn** [comment]
@smelukov ok fix it tonight

**Comment by husayt** [comment]
@smelukov can you also try that in latest. I added MUI demo with styled components. it will be useful to see how this issue reveals itself in that case.

**Comment by smelukov** [comment]
Reproduction example uses the latest version of plugin

**Comment by husayt** [comment]
what I mean, there is already an example with styled components. Can you try do reproducation with them. Is it just adding styled-component to shared, or there is something else as well?

**Comment by zhangHongEn** [comment]
thanks, I probably know the cause of this problem

**Comment by smelukov** [comment]
@husayt just add styled components into shared

**Comment by husayt** [comment]
@zhangHongEn I am not sure if this is fixed. I still get 
![image](https://github.com/user-attachments/assets/f325d1d3-d51b-464f-8efc-189ecf62cdce)
in the latest, when i set
```
     "@emotion/styled": { singleton: true, },
```

**Comment by zhangHongEn** [comment]
@husayt I tried but couldn't reproduce it. It may not be the same issue

**Comment by husayt** [comment]
> @husayt I tried but couldn't reproduce it. It may not be the same issue

i have created a reproduction in a separate issue here #61. Hopefully, this will be straightforward
