### ISSUE TITLE
Is a new plugin supports trailing / in imports to shared libraries?

### ISSUE THREAD

**Issue by smelukov** [module-federation/vite#59]
@zhangHongEn
https://webpack.js.org/concepts/module-federation/
![image](https://github.com/user-attachments/assets/2142db23-8560-4dfc-b5d8-52f4870ed188)

```
shared: {
  'lodash/': {
    singleton: true
  }
}
```

all the import will be treated as shared:
```ts
import _ from 'lodash';
import fp from 'lodash/fp';
import array from 'lodash/array';
import object from 'lodash/fp/object';
```

**Comment by smelukov** [comment]
I've checked and the answer is no :(
@zhangHongEn Could you please support this feature?

**Comment by zhangHongEn** [comment]
Yes, same as #40, I will support it soon

**Comment by smelukov** [comment]
thanks

**Comment by gioboa** [comment]
I close it because it's a duplicate
