### ISSUE TITLE
There are problems when using the `@vue/composition-api`.

### ISSUE THREAD

**Issue by He110te4m** [module-federation/vite#6]
When I ran [the sample repo](https://github.com/gioboa/vue-microfrontend-demo/tree/vue2_implementation), I noticed a bit of a problem.

When I modify [`Count.vue`](https://github.com/gioboa/vue-microfrontend-demo/blob/vue2_implementation/remote/src/components/Counter.vue) to the following code:

```vue
<script lang="ts">
import { defineComponent, ref } from "@vue/composition-api";

export default defineComponent({
  // change to setup syntax
  setup: () => {
    const count = ref(0);

    return {
      count,
    };
  },
});
</script>

<template>
  <button style="
        border: 0 solid #e2e8f0;
        margin-top: 10px;
        background-color: rgb(246, 179, 82);
        border-radius: 0.25rem;
        font-weight: 700;
        padding: 0.5rem 1rem 0.5rem 1rem;
        color: rgb(24, 24, 24);
      " @click="count++">
    Remote counter: {{ count }}
  </button>
</template>
```

This is the result of the run:

![image](https://github.com/module-federation/vite/assets/16161582/cf377679-3e83-454a-8690-e7f7f061f24b)

As we can see, the remote project is missing data.

I got the following misinformation from console: `[vue-composition-api] must call Vue.use(VueCompositionAPI) before using any function.`

In fact, the `@vue/composition-api` needs to be initialize ( `Vue.use` ), then it can be used.

This error occurs because the `@vue/composition-api` is not shared and the initialization process is lost.

I still get an error when I try to share the `@vue/composition-api`:

![image](https://github.com/module-federation/vite/assets/16161582/084f8a55-a506-4f59-8a42-ce5a4a3cb310)

Seems to be dependent on the loading order of the problem, can someone give me some advice?

**Comment by He110te4m** [comment]
When I use a shared `Vue` with a non-shared `@vue/composition-api`, and provide an entry file for initialized, the code in remote is lost reactive.

```typescript
// entry.ts
import Vue from 'vue'
import VCA from '@vue/composition-api'
import App from './App.vue'

Vue.use(VCA)

export default App
```

![image](https://github.com/module-federation/vite/assets/16161582/3219711b-985c-4626-9338-f9def35e72c9)

**Comment by gioboa** [comment]
So with the second approach is working right?
I'm not an expert in Vue 👀 is the first solution better?

**Comment by He110te4m** [comment]
I went through the source code for the composition-api and found [this line](https://github.com/vuejs/composition-api/blob/main/src/index.ts#L24).

So I mounted `Vue` on window.

I managed to resolve the error, but a variable with the same name has been repeatedly defined.

**Comment by He110te4m** [comment]
From the point of view of the exception, the problem is in [this line](https://github.com/vuejs/composition-api/blob/06357e799ed9196700861a9ab221c3bef8dc685b/src/utils/instance.ts#L22).

When I load the component via remote, the data is already defined in the component.

So I get an error message with a repeated definition.

**Comment by gioboa** [comment]
Thanks for your report @He110te4m 
Can I do something to solve this problem?

**Comment by He110te4m** [comment]
> Thanks for your report @He110te4m Can I do something to solve this problem?

I've pretty much figured out that my problem can be solved by modifying the following code:

```diff
// file path: host/src/bootstrap.ts

import VCA, { h } from "@vue/composition-api";
import Vue from "vue";
import App from "./App.vue";

init();

function init() {
+  window.Vue = Vue;
  Vue.use(VCA);

  const app = new Vue({
    render: () => h(App),
  });

  app.$mount("#app");
}
```

After that I get a warning about the repeated definition of data in the composition API, but that's not the plug-in's problem, it's the composition API's.

That is, the solution to the problem is set `Vue` on the window.

In addition to this, I found a few other exceptions, maybe I need to open an issue separately.

All in all, I will close this issue.

**Comment by gioboa** [comment]
Thanks for your commitment 💪
