### ISSUE TITLE
v1.0.0: Plugin placing files in npm dependency can be an issue when building

### ISSUE THREAD

**Issue by SanseroGames** [module-federation/vite#66]
The plugin currently writes files to the npm-package dependency `an-empty-js-file`. There are two problems with this:

First, we use pnpm with `hoist=false` in .npmrc. This causes pnpm not to symlink the `an-empy-js-file` to the node_modules of the project that uses the vite plugin.  The dependency is still available to the vite plugin but vite itself does not find the package anymore so the build fails, as files are not found. This can be solved by also adding `an-empty-js-file` as a dependency to the project so pnpm symlinks the package. However, this feels like a weird way to solve this issue, as it is not really a dependency of the project.

The second problem we encountered is that our build system does not like a target editing its dependencies. We use [Bazel](https://bazel.build/) with [rules_js](https://docs.aspect.build/rulesets/aspect_rules_js/) that uses pnpm under the hood to build our web apps. Bazel makes dependencies read-only, which prevents this vite plugin from placing or modifying any files into the `an-empty-js-file` package.

Would you mind to elaborate why it is necessary for the plugin to place files to a different npm package? Could this be done without that? I'd be open to try to help find an alternative solution that would not require changing a dependency.

**Comment by zhangHongEn** [comment]
The node_modules module (such as vue, react) will be pre-built by vite, and no plugin can interfere with this process, including the earliest executed resolveId api.
The file name of the pre-built node_modules will become chunk-hash.js, so I can't proxy it and can't implement shared.
So I use alias to generate a new file before pre-building to proxy node_modules (because plugins can't interfere and virtual modules can't be used)

**Comment by zhangHongEn** [comment]
Use [cacheDir path](https://vitejs.dev/config/shared-options.html#cachedir) to replace `an-empty-js-file` 
Setting [this path](https://github.com/module-federation/vite/blob/9ec5af07ead25fb7365d6c67142615028fb30e21/src/virtualModules/virtualShared_preBuild.ts#L26) to `optimizeDeps.include` should solve this problem

**Comment by SanseroGames** [comment]
Thank you for your replies. I think I understand now what you're trying to accomplish. I'm having a look at it to see how the vite cache path could be used instead.

**Comment by gioboa** [comment]
Closed by #67
