### ISSUE TITLE
Whether the shared chunk can be merged ?

### ISSUE THREAD

**Issue by He110te4m** [module-federation/vite#7]
When shared has too many dependencies, it causes too many network requests.

Is it possible to let users merge dependencies themselves?

I know this affects the dependent version rollback problem.

But in many cases, the user will be their own convention dependent version.

Let the user set it to not merge for dependencies that will differ.

There should be at least one option for the user to select.

PS: I Can't find the github repository for `@softarc/native-federation`, so I'll just have to ship it here first. I would appreciate it if someone could give me the warehouse address for this project

**Comment by gioboa** [comment]
You can use this [this configuration](https://github.com/module-federation/module-federation-examples/blob/88c252fbc3fdc3262e0d8e3d03a945276bd0a165/vite-vue-microfrontends/host/module-federation/federation.config.cjs#L9) to managed shared dependencies

**Comment by He110te4m** [comment]
> You can use this [this configuration](https://github.com/module-federation/module-federation-examples/blob/88c252fbc3fdc3262e0d8e3d03a945276bd0a165/vite-vue-microfrontends/host/module-federation/federation.config.cjs#L9) to managed shared dependencies

There's been a bit of a misunderstanding here. I don't mean automatically sharing dependencies.

If I share Vue and vue-router at build time, I need to make two requests to either Dev or prod, one for Vue and the other for vue-router.

I'd like to reduce the number of requests by, for example, merging Vue and vue-router, which in fact often work together on my project.

**Comment by gioboa** [comment]
I see, so you would like to bundle share dependencies together. I think this could be hard to achieve without changing native federation library 🤔

**Comment by He110te4m** [comment]
Yes, but I can't find the repo of native federation.

Without this feature, I might need to think about HTTP 2.

**Comment by gioboa** [comment]
Here is [the code](https://www.npmjs.com/package/@softarc/native-federation?activeTab=code)
@manfredsteyer and @rainerhahnekamp are the authors of this amazing library

**Comment by rainerhahnekamp** [comment]
Thanks @gioboa, but unfortunately, I can't take the credit for it. Maybe I can earn it by adding some tests here and there and working on GitHub actions for integration tests. 

But module-federation is mainly @manfredsteyer and @mikezks

**Comment by gioboa** [comment]
I saw you here, anyway thanks for your kind reply 
![Uploading Screenshot_20230517-130813.jpg…]()

**Comment by mikezks** [comment]
@He110te4m:

You can find the repository [here](https://github.com/angular-architects/module-federation-plugin).

@rainerhahnekamp, @gioboa:

Thx for tagging us.
The NPM info shows all collaborators of a specific organisation (here [@]softarc), therefore @rainerhahnekamp is mentioned (BTW, he published a great package recently [Sheriff](https://www.npmjs.com/package/@softarc/sheriff-core)).

@manfredsteyer

We should add the GitHub repo link into the NPM package's metadata.


On topic:

Currently, Native Federation does not support grouped bundles, but we know that there is interest to support such a feature.
@He110te4m, feel free to open a feature request in the [Native Federation](https://github.com/angular-architects/module-federation-plugin) repo to discuss this further.

**Comment by He110te4m** [comment]
Thank you very much for your replies to this question.

I will submit a new issue in the corresponding repo.
