### ISSUE TITLE
v1.0.0: Using of trailing / in shared breaks our project

### ISSUE THREAD

**Issue by smelukov** [module-federation/vite#77]
@zhangHongEn
Trailing `/` was implemented in https://github.com/module-federation/vite/issues/40 and works wrong, so it breaks our project.

We use some uikit library `our-uikit-library` in shared with trailing `/`:
```
shared: {
  'our-uikit-library/': {
    singleton: true
  }
}
```

We have these errors:

```
✘ [ERROR] No loader is configured for ".ttf" files: ../../node_modules/our-uikit-library/lib/styles/fonts/Inter-Bold.ttf

    ../../node_modules/our-uikit-library/lib/styles/fonts.css:34:11:
      34 │   src: url('fonts/Inter-Bold.ttf');
         ╵            ~~~~~~~~~~~~~~~~~~~~~~

✘ [ERROR] No loader is configured for ".ttf" files: ../../node_modules/our-uikit-library/lib/styles/fonts/PTMono-Regular.ttf

    ../../node_modules/our-uikit-library/lib/styles/fonts.css:49:11:
      49 │   src: url('fonts/PTMono-Regular.ttf');
         ╵            ~~~~~~~~~~~~~~~~~~~~~~~~~~

4:33:52 PM [vite] error while updating dependencies:
Error: Build failed with 11 errors:
../../node_modules/our-uikit-library/lib/styles/fonts.css:4:11: ERROR: No loader is configured for ".ttf" files: ../../node_modules/our-uikit-library/lib/styles/fonts/Inter-Thin.ttf
../../node_modules/our-uikit-library/lib/styles/fonts.css:9:11: ERROR: No loader is configured for ".ttf" files: ../../node_modules/our-uikit-library/lib/styles/fonts/Inter-ExtraLight.ttf
../../node_modules/our-uikit-library/lib/styles/fonts.css:14:11: ERROR: No loader is configured for ".ttf" files: ../../node_modules/our-uikit-library/lib/styles/fonts/Inter-Light.ttf
../../node_modules/our-uikit-library/lib/styles/fonts.css:19:11: ERROR: No loader is configured for ".ttf" files: ../../node_modules/our-uikit-library/lib/styles/fonts/Inter-Regular.ttf
../../node_modules/our-uikit-library/lib/styles/fonts.css:24:11: ERROR: No loader is configured for ".ttf" files: ../../node_modules/our-uikit-library/lib/styles/fonts/Inter-Medium.ttf
...
    at failureErrorWithLog (/path/to/project/node_modules/esbuild/lib/main.js:1472:15)
    at /path/to/project/node_modules/esbuild/lib/main.js:945:25
    at /path/to/project/node_modules/esbuild/lib/main.js:1353:9
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
```

We do not have any of these errors when we use the module federation plugin for webpack. Moreover, we use cssinjs and our project does not import any CSS files.
In this case, we see how something imports a CSS file and this CSS file imports some fonts.
This is unexpected behaviour
Seems like trailing `/` forces vite to import all of the modules in shared package, even not imported by the project

**Comment by zhangHongEn** [comment]
I'm not sure if it's related to nx monorepo. I tried to reproduce it and didn't encounter any exceptions. Can you provide a demo?

**Comment by smelukov** [comment]
> There shouldn't be this problem, maybe other plugins automatically import css?

Nope, this error appears only with vite mf plugin (last update)

**Comment by zhangHongEn** [comment]
<img width="984" alt="image" src="https://github.com/user-attachments/assets/d8f4fda0-1a01-49c2-9ebe-815d74e633f2">
<img width="893" alt="image" src="https://github.com/user-attachments/assets/3f3f1943-8a72-46c0-866c-5f773e389bca">
<img width="1027" alt="image" src="https://github.com/user-attachments/assets/abdd46cf-2d57-4f23-881c-87242624f579">

**Comment by zhangHongEn** [comment]
You can find `localSharedImportMap.js` in the network request, which contains all shared

**Comment by smelukov** [comment]
I see css-import in this map, but without mf plugin everything works without errors

**Comment by smelukov** [comment]
![image](https://github.com/user-attachments/assets/e308beec-1bcd-459f-aa18-21d723e9dbc7)
Also, sometime localSharedImportMap just stuck
Sometimes restarting Vite helps, sometimes not.

**Comment by smelukov** [comment]
@zhangHongEn I've created a reproduction: https://github.com/smelukov/mf-vite-nx-bug/tree/trailing-slash-bug/packages/my-lib (brach **trailing-slash-bug**)
We have some package with css [packages/my-lib](https://github.com/smelukov/mf-vite-nx-bug/tree/trailing-slash-bug/packages/my-lib)
This package [is in shared section](https://github.com/smelukov/mf-vite-nx-bug/blob/trailing-slash-bug/packages/my-app/vite.config.ts#L30) with trailing slash
We import this module [here](https://github.com/smelukov/mf-vite-nx-bug/blob/trailing-slash-bug/packages/my-app/src/main.tsx#L3)

- run `npm start`
- go to http://localhost:4201/ and see a white screen
- look at vite console and see
```
✘ [ERROR] No loader is configured for ".ttf" files: ../my-lib/lib/styles/fonts/PTMono-Regular.ttf

    ../my-lib/lib/styles/fonts.css:4:11:
      4 │   src: url('fonts/PTMono-Regular.ttf');
        ╵            ~~~~~~~~~~~~~~~~~~~~~~~~~~

7:32:14 AM [vite] error while updating dependencies:
Error: Build failed with 1 error:
../my-lib/lib/styles/fonts.css:4:11: ERROR: No loader is configured for ".ttf" files: ../my-lib/lib/styles/fonts/PTMono-Regular.ttf
    at failureErrorWithLog (/path/to/project/node_modules/esbuild/lib/main.js:1472:15)
    at /path/to/project/node_modules/esbuild/lib/main.js:945:25
    at /path/to/project/node_modules/esbuild/lib/main.js:1353:9
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
```
- stop `npm start`
- remote `my-lib` from shared section
- run `npm start` again
- go to http://localhost:4201/ and see that all is ok

**Comment by zhangHongEn** [comment]
ok
