### ISSUE TITLE
Vue: `forceViteRestart` function does not always work.

### ISSUE THREAD

**Issue by He110te4m** [module-federation/vite#8]
[`forceViteRestart`](https://github.com/gioboa/vue-microfrontend-demo/blob/vue2_implementation/shared/forceViteRestart.js) uses a fixed delay to restart vite, but this does not always work.

Sometimes I need to rerun `npm run dev` several times.

Can it be integrated into the plugin automatically reload like [`vite-plugin-restart`](https://github.com/antfu/vite-plugin-restart/blob/main/src/index.ts#L78)?

**Comment by gioboa** [comment]
Hi, yes sure.
You can open a PR here https://github.com/gioboa/vue-microfrontend-demo
Then we can also change the examples in module-federation/examples

**Comment by He110te4m** [comment]
> Hi, yes sure. You can open a PR here https://github.com/gioboa/vue-microfrontend-demo Then we can also change the examples in module-federation/examples

No, I think there's been a misunderstanding.
In the example project, I found that the Dev script needs to manually restart each time to make the plug-in's modified configuration entry take effect.
Perhaps we can build this restart logic into the `@module-federation/Vite' .

**Comment by gioboa** [comment]
This could be a good solution

**Comment by He110te4m** [comment]
I've written a custom plugin to do this.

When using Vite serve, there is no need to execute an additional restart script.

Also, when I modify the Federation, Vite is automatically restarted.

The code is as follows:

```typescript
import { readFileSync, writeFileSync } from 'node:fs'
import { type Plugin } from 'vite'
import ViteRestart from 'vite-plugin-restart'

const reloadedSet = new Set<string>()
function reload() {
  const filename = 'vite.config.ts'
  setTimeout(() => {
    writeFileSync(filename, readFileSync(filename, 'utf8'))
  }, 2000)
}

/** 检查 CSS 是否被污染的 vite 插件 */
export function autoReloadPlugin(): Plugin[] {
  return [
    {
      name: 'vite-plugin-micro-service-auto-reload',
      apply: 'serve',
      enforce: 'post',
      buildStart() {
        const service = process.cwd()
        if (!service || reloadedSet.has(service)) {
          return
        }
        reloadedSet.add(service)
        reload()
      },
    },
    ViteRestart({
      restart: [
        'module-federation/federation.config.js',
      ],
    }),
  ]
}
```

**Comment by gioboa** [comment]
Great, thanks for that. Are you using this package for a Vue project?

**Comment by gioboa** [comment]
Thanks for this feedbacks, I will include the logic in the package

**Comment by He110te4m** [comment]
Hello @gioboa .

I updated the code for the plugin.
We can actually trigger the update by listening for server events without a fixed delay.

I've found that when I share code with others, it doesn't work with fixed delays due to their low computer configuration.
When the code is run, the Vite is not initialized.

It would be more general to control trigger timing through server events.

```
import { readFileSync, writeFileSync } from 'node:fs'
import { type Plugin } from 'vite'
import ViteRestart from 'vite-plugin-restart'

const id = process.cwd()
const reloadedSet = new Set<string>()
function reload() {
  const filename = 'vite.config.ts'
  setTimeout(() => {
    writeFileSync(filename, readFileSync(filename, 'utf8'))
  }, 0)
}

/** vite 模块联邦自动 restart 插件 */
export function autoReloadPlugin(): Plugin[] {
  return [
    {
      name: 'vite-plugin-micro-service-auto-reload',
      apply: 'serve',
      enforce: 'post',
      configureServer({ httpServer }) {
        httpServer?.once('listening', () => {
          globalThis.console.log('🚀 ~ file: index.ts:25 ~ ws.on ~ id:', id, reloadedSet)
          if (!reloadedSet.has(id)) {
            reloadedSet.add(id)
            reload()
          }
        })
      },
    },
    ViteRestart({
      restart: [
        'module-federation/federation.config.js',
        'node_modules/@dsp/configs/federation/shared.js',
      ],
    }),
  ]
}
```

**Comment by He110te4m** [comment]
It's worth mentioning that I tried using `server.restart` to replace `writeFileSync`.

Surprisingly, this is not possible, and the Vite is not initialized after `restart`.

Users need to visit the remote page first, after the initialization, to work properly.

Oddly enough, `restart` does work during development.

That is, `restart` must occur after the page visit.

**Comment by gioboa** [comment]
🤔 that's a strange behaviour. Let's step back a bit. Why do we need this implementation? Is there a specific vite configuration that solves this problem?

**Comment by He110te4m** [comment]
According to what I know, the problem stems from that [Vite does not support dynamics externals](https://github.com/module-federation/vite/blob/main/src/dev-externals-mixin.ts#L4).

It may also be that [plugin have been added on config resolved](https://github.com/module-federation/vite/blob/main/src/dev-externals-mixin.ts#L20).

If we don't restart, there will be a problem with Vite's virtual module parsing, and Vite will not recognize id starting with `\0`.

We get this error:

```
Error: Unable to resolve specifier '__x00__/vite/vueComponentNormalizer' imported from http://localhost:4173/src/App.vue
```

**Comment by He110te4m** [comment]
I think I found the problem.

On [this line](https://github.com/module-federation/vite/blob/main/src/dev-externals-mixin.ts#L19), the `reg` replaces all `/@id/`, because externals are empty at this point.

This causes the module ID that is not external to be replaced as well.

This includes virtual modules.

So the plug-in is not working properly and restart is required.

**Comment by He110te4m** [comment]
Yes, I downloaded the plugin code locally.

When I modified `init` into `config` hook, the plugin worked (albeit slower than normal) .

**Comment by He110te4m** [comment]
There's also a reason why the restart function doesn't work.

It actually works, but because the host triggered it first, it didn't trigger remote's restart, which makes it a serial execution, which is very slow.

In my perception, it becomes not working.

**Comment by He110te4m** [comment]
Hello @gioboa , to fix this issue, I create an PR.

Please review it if you have time.
