### ISSUE TITLE
v1.0.0 Add new config typings

### ISSUE THREAD

**Issue by tkachukcha** [module-federation/vite#83]
First of all, thank you for your efforts! You saved 10 hours of migrating from webpack to vite being wasted in vain! 

As for issue: at the moment I get ts error when passing new config options. It expects 0.2.8 config type at the moment

This is what plugin expects:
`federation: (params: BuildHelperParams) => any`

**Comment by zhangHongEn** [comment]
are you using `@module-federation/vite@next`?

**Comment by zhangHongEn** [comment]
![image](https://github.com/user-attachments/assets/8b63e6d5-edfd-4110-a102-3a3d0e33c7a1)
Can check the version number

**Comment by tkachukcha** [comment]
I use the latest one, 1.0.0-alpha-1aa30c0

**Comment by tkachukcha** [comment]
Hm, I guess it's some caching problems. Other problem doesn't have this problem.
