### ISSUE TITLE
Error sharing "react-dom" in dev mode

### ISSUE THREAD

**Issue by RussellCanfield** [module-federation/vite#88]
Everything has been working pretty well so far 🙂 I did run into one issue when sharing "react-dom" in dev mode:

```javascript
chunk-5GRLQEB4.js?v=8f475596:27 Uncaught (in promise) TypeError: factory is not a function
    at chunk-5GRLQEB4.js?v=8f475596:27:29
    at async chunk-5GRLQEB4.js?v=8f475596:34:97
```

This line in the bundle: 
```javascript
const mfproxyawaitrequire_vite_mf_2_host_loadShare_react_mf_2_dom_loadShare = await require_vite_mf_2_host_loadShare_react_mf_2_dom_loadShare();
```

It seems like when it calls into the runtime, the host's options -> shared, is missing react-dom, although the Vite plugin specifies it.

Maybe in here?
https://github.com/module-federation/vite/blob/b1bba84c563f5eea7e92aad250f422d0b624f664/src/plugins/pluginProxySharedModule_preBuild.ts#L40

**Comment by zhangHongEn** [comment]
Can you provide a reproducible example?
Also, does it reproduce when you run this [example](https://github.com/module-federation/vite/blob/main/examples/vite-vite/vite-remote/vite.config.js)?

**Comment by tduforet** [comment]
Hello, I have the same error with my project using vite for the host and webpack for remotes but only on preview mode after a build. It works correctly in dev mode.

**Comment by gioboa** [comment]
Can you create a basic reproduction repo please?

**Comment by tduforet** [comment]
I tried but I don't have any errors with a simple project.

The error occurs here only with build and preview mode. It works correctly in dev mode.
<img width="885" alt="Capture d’écran 2024-10-29 à 16 13 12" src="https://github.com/user-attachments/assets/f8d4a1ab-e1bf-458f-aab5-e48ba5e19509">

with these shared dependencies
<img width="317" alt="Capture d’écran 2024-10-29 à 16 13 34" src="https://github.com/user-attachments/assets/3f580f38-1133-4f4a-9f2c-cd37679fd31e">

But I understand if you can't do anything without a reproduction repo.

**Comment by gioboa** [comment]
@tduforet are you using the latest release ?

**Comment by tduforet** [comment]
Yes, it wasn't the latest when I had the problem the first time. I updated the version to the latest and I always have the problem.

**Comment by gioboa** [comment]
I added the config below in the react example and it's working fine.
```
'react-dom': {
	singleton: true,
	strictVersion: true,
	requiredVersion: '18.3.1',
},
'react-router-dom': {
	singleton: true,
},
```
You can try to figure out step by step the piece of code that is creating that error. Without a failing example it's impossible to face the issue. I'm sorry

**Comment by tduforet** [comment]
Yes I understand, I try to add some log, the factory is false si maybe there is a problem on loadShare method for react.

Thanks for your help.

**Comment by zhangHongEn** [comment]
Here’s an important issue. It only occurs in build mode, and it would be great if you could provide a reproducible example.

**Comment by tduforet** [comment]
Hello, I removed one by one the different plugins I had in my project and it seems the plugin vite-plugin-svgr is the problem.
When I add it in a simple project with only the react plugin and federation plugin I also have the error.

**Comment by tduforet** [comment]
For now I don't understand why but it works only if I use the svgr plugin after the federation plugin in the vite config.

**Comment by zhangHongEn** [comment]
> For now I don't understand why but it works only if I use the svgr plugin after the federation plugin in the vite config.
`
plugins: [
  federation(),
  svgr()
]
`

Will adjusting the order solve the problem? That would be great!

**Comment by tduforet** [comment]
Yes it works when svgr is after federation but I don't know why 😅

**Comment by zhangHongEn** [comment]
The two plugins with `"enforce": "pre"` are conflicting; optimization could be considered.

**Comment by gioboa** [comment]
Yep, we need to consider it because we can have this kind of errors with many other plugins.

**Comment by zmzlois** [comment]
was thinking wrap federation under your own plugin and add a `load()=>{}` that does nothing to trick the AST re-parse
