### ISSUE TITLE
vite-vite example does not work

### ISSUE THREAD

**Issue by nicotu01** [module-federation/vite#89]
I try to start vite-vite example like that : 
> pnpm i 
> cd examples/vite-vite/vite-remote && pnpm preview
> cd examples/vite-vite/vite-host && pnpm dev 

And I have errors in console when I visit the Host : 
```
Uncaught TypeError: factory is not a function
    at chunk-NYMJEQIN.js:27:29
    at async chunk-NYMJEQIN.js:33:1
Uncaught SyntaxError: Cannot use import statement outside a module
```

**Comment by zhangHongEn** [comment]
I couldn't reproduce the issue, but I tried to fix a possible cause.

**Comment by zhangHongEn** [comment]
If you are willing, can you help me try to see if the repair is effective?
https://github.com/zhangHongEn/vite

**Comment by nicotu01** [comment]
Yes, the host load remotes.
But I have many errors in the console : 
![error-mfv](https://github.com/user-attachments/assets/06a1c7bd-f238-4540-bea2-0398638e2094)

**Comment by zhangHongEn** [comment]
This error is normal, you can refer to this issue. Currently, you can close the manifest

https://github.com/module-federation/vite/issues/87

---- Replied Message ----
| From | ***@***.***> |
| Date | 09/17/2024 19:28 |
| To | module-federation/vite ***@***.***> |
| Cc | zhn ***@***.***>,
Comment ***@***.***> |
| Subject | Re: [module-federation/vite] vite-vite example does not work (Issue #89) |

Yes, the host load remotes.
But I have many errors in the console :
error-mfv.png (view on web)

**Comment by nicotu01** [comment]
thanks

**Comment by zhangHongEn** [comment]
So, only with this new fix can you load it correctly? I'm asking because my device can function normally without using this repair

---- Replied Message ----
| From | ***@***.***> |
| Date | 09/17/2024 19:38 |
| To | module-federation/vite ***@***.***> |
| Cc | zhn ***@***.***>,
Comment ***@***.***> |
| Subject | Re: [module-federation/vite] vite-vite example does not work (Issue #89) |

thanks

**Comment by nicotu01** [comment]
Yes, I confirm.
Without the fix, I have the error below :  
![factory_error](https://github.com/user-attachments/assets/328625e9-908e-4d7d-beb3-202b67ca39f4)

**Comment by nicotu01** [comment]
As you mentioned, propably the same error : https://github.com/module-federation/vite/issues/88

**Comment by zhangHongEn** [comment]
Thank you, I will fix it today

---- Replied Message ----
| From | ***@***.***> |
| Date | 09/17/2024 20:09 |
| To | module-federation/vite ***@***.***> |
| Cc | zhn ***@***.***>,
Comment ***@***.***> |
| Subject | Re: [module-federation/vite] vite-vite example does not work (Issue #89) |

As you mentioned, propably the same error : #88
