### ISSUE TITLE
Can't use the package without pnpm

### ISSUE THREAD

**Issue by kalucki** [module-federation/vite#93]
I wanted to use the package for my project, but it's not possible wihtout pnpm. I'm using yarn and when doing `yarn add @module-federation/vite` I'm getting:

```
Exit code: 127
Command: pnpm run build
Arguments:
Directory: /Users/piotrek/Lagrange/landing-page-mf/node_modules/@module-federation/vite
Output:
/bin/sh: pnpm: command not found
```
Is it possible to use it without being forced to migrate to pnpm?

**Comment by zhangHongEn** [comment]
@gioboa We can remove the postinstall script for now

**Comment by zhangHongEn** [comment]
@kalucki You can temporarily use the previous version: 1.0.0-alpha-31ab3f9.

**Comment by gioboa** [comment]
We can change the package.json scripts to use npm. If you are using yarn you have npm too.
Does that make sense?

**Comment by gioboa** [comment]
@kalucki btw you can download the package from npm. It's published, it's compiled and ready to be used

**Comment by zhangHongEn** [comment]
The postinstall script causes pnpm to be executed automatically every time

**Comment by kalucki** [comment]
It's exactly what @zhangHongEn says. The script runs after install, doesn't matter if I use yarn or npm. If you don't pnpm it will break

**Comment by kalucki** [comment]
your `postinstall` is running `pnpm run build`, so maybe checking for `pnpm` installed and then defaulting to `npm` could be a solution?

**Comment by kalucki** [comment]
> We can change the package.json scripts to use npm. If you are using yarn you have npm too.
> Does that make sense?

That would be the easiest solution for sure.

**Comment by zhangHongEn** [comment]
@gioboa We can ignore whether the examples can run simply for now. It seems there’s an issue with running build in the postinstall script

**Comment by zhangHongEn** [comment]
`mkdir test3 && cd test3 && npm init -y && pnpm install @module-federation/vite@latest -D`

`
Wrote to package.json:

{
  "name": "test3",
  "version": "1.0.0",
  "description": "",
  "main": "index.js",
  "scripts": {
    "test": "echo \"Error: no test specified\" && exit 1"
  },
  "keywords": [],
  "author": "",
  "license": "ISC"
}


Packages: +11
+++++++++++
Progress: resolved 11, reused 11, downloaded 0, added 11, done
node_modules/.pnpm/@module-federation+vite@1.0.0-alpha-f2257a4/node_modules/@modnode_modules/.pnpm/@module-federation+vite@1.0.0-alpha-f2257a4/node_modules/@module-federation/vite: Running postinstall script, failed in 322ms
.../node_modules/@module-federation/vite postinstall$ pnpm run build
│ > @module-federation/vite@1.0.0-alpha-f2257a4 build /Users/zhanghongen/Desk…
│ > rimraf lib && microbundle --no-sourcemap --compress=false
│ sh: rimraf: command not found
│  ELIFECYCLE  Command failed.
│  WARN   Local package.json exists, but node_modules missing, did you mean t…
└─ Failed in 322ms at /Users/zhanghongen/Desktop/open-code/test3/node_modules/.pnpm/@module-federation+vite@1.0.0-alpha-f2257a4/node_modules/@module-federation/vite
 ELIFECYCLE  Command failed with exit code 1.
 `

**Comment by gioboa** [comment]
I see, so the `postinstall` script is running for the consumer too. 🤔

**Comment by kalucki** [comment]
Confirmed. Problem solved. Thank you for a quick response guys, awesome thing that you're building here 👍
