### ISSUE TITLE
Handle Promise Based Dynamic Remotes like in Webpack

### ISSUE THREAD

**Issue by tduforet** [module-federation/vite#98]
To be able to use a remote on different environment I use Promise Based Dynamic Remotes with the webpack module federation.
https://webpack.js.org/concepts/module-federation/#promise-based-dynamic-remotes

Is it possible to have the same in this vite plugin ?

**Comment by zhangHongEn** [comment]
That one is outdated, use this one
https://module-federation.io/configure/runtimeplugins.html
